// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NinjaOne.Client.V2.Billing.Invoices.Item
{
    /// <summary>
    /// Representation of a ninja billing invoice.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InvoicesGetResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Basic agreement information.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse_agreement? Agreement { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse_agreement Agreement { get; set; }
#endif
        /// <summary>Invoice products/line items coming from agreements.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse_agreementProducts>? AgreementProducts { get; set; }
#nullable restore
#else
        public List<global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse_agreementProducts> AgreementProducts { get; set; }
#endif
        /// <summary>Whether online ACH payments are allowed.</summary>
        public bool? AllowOnlineAchPayments { get; set; }
        /// <summary>Whether online credit card payments are allowed.</summary>
        public bool? AllowOnlineCreditCardPayments { get; set; }
        /// <summary>App user name who created/modified the invoice.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AppUserName { get; set; }
#nullable restore
#else
        public string AppUserName { get; set; }
#endif
        /// <summary>Bill content information for invoice.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse_billContent? BillContent { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse_billContent BillContent { get; set; }
#endif
        /// <summary>Billing period end date.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BillingPeriodEndDate { get; set; }
#nullable restore
#else
        public string BillingPeriodEndDate { get; set; }
#endif
        /// <summary>Billing period start date.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BillingPeriodStartDate { get; set; }
#nullable restore
#else
        public string BillingPeriodStartDate { get; set; }
#endif
        /// <summary>Client information associated with this invoice</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse_client? Client { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse_client Client { get; set; }
#endif
        /// <summary>Created date.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreateTime { get; set; }
#nullable restore
#else
        public string CreateTime { get; set; }
#endif
        /// <summary>Currency code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Currency { get; set; }
#nullable restore
#else
        public string Currency { get; set; }
#endif
        /// <summary>Whether the invoice is deleted.</summary>
        public bool? Deleted { get; set; }
        /// <summary>Discount amount.</summary>
        public double? Discount { get; set; }
        /// <summary>Due date.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DueDate { get; set; }
#nullable restore
#else
        public string DueDate { get; set; }
#endif
        /// <summary>Error description if failed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ErrorDescription { get; set; }
#nullable restore
#else
        public string ErrorDescription { get; set; }
#endif
        /// <summary>External tax information.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse_externalTax? ExternalTax { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse_externalTax ExternalTax { get; set; }
#endif
        /// <summary>Failure reason if invoice processing failed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FailureReason { get; set; }
#nullable restore
#else
        public string FailureReason { get; set; }
#endif
        /// <summary>Whether invoice has active integration data.</summary>
        public bool? HasActiveIntegrationData { get; set; }
        /// <summary>Unique identifier of the invoice.</summary>
        public int? Id { get; set; }
        /// <summary>Billing interval.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Interval { get; set; }
#nullable restore
#else
        public string Interval { get; set; }
#endif
        /// <summary>Invoice date.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InvoiceDate { get; set; }
#nullable restore
#else
        public string InvoiceDate { get; set; }
#endif
        /// <summary>Invoice generation type.</summary>
        public global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse_invoiceGenerationType? InvoiceGenerationType { get; set; }
        /// <summary>Invoice note field.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InvoiceNote { get; set; }
#nullable restore
#else
        public string InvoiceNote { get; set; }
#endif
        /// <summary>Invoice number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InvoiceNumber { get; set; }
#nullable restore
#else
        public string InvoiceNumber { get; set; }
#endif
        /// <summary>Invoice notes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Notes { get; set; }
#nullable restore
#else
        public List<string> Notes { get; set; }
#endif
        /// <summary>Invoice products/line items added directly to the invoice.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse_products>? Products { get; set; }
#nullable restore
#else
        public List<global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse_products> Products { get; set; }
#endif
        /// <summary>Invoice status.</summary>
        public global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse_status? Status { get; set; }
        /// <summary>Subtotal amount before discount.</summary>
        public double? SubTotal { get; set; }
        /// <summary>Subtotal after discount.</summary>
        public double? SubTotalWithDiscount { get; set; }
        /// <summary>Tax rate applied.</summary>
        public double? TaxRate { get; set; }
        /// <summary>Invoice products/line items coming from tickets.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse_ticketProducts>? TicketProducts { get; set; }
#nullable restore
#else
        public List<global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse_ticketProducts> TicketProducts { get; set; }
#endif
        /// <summary>Total amount including tax.</summary>
        public double? Total { get; set; }
        /// <summary>Total tax amount.</summary>
        public double? TotalTax { get; set; }
        /// <summary>Last update date.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdateTime { get; set; }
#nullable restore
#else
        public string UpdateTime { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse"/> and sets the default values.
        /// </summary>
        public InvoicesGetResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "agreement", n => { Agreement = n.GetObjectValue<global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse_agreement>(global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse_agreement.CreateFromDiscriminatorValue); } },
                { "agreementProducts", n => { AgreementProducts = n.GetCollectionOfObjectValues<global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse_agreementProducts>(global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse_agreementProducts.CreateFromDiscriminatorValue)?.AsList(); } },
                { "allowOnlineAchPayments", n => { AllowOnlineAchPayments = n.GetBoolValue(); } },
                { "allowOnlineCreditCardPayments", n => { AllowOnlineCreditCardPayments = n.GetBoolValue(); } },
                { "appUserName", n => { AppUserName = n.GetStringValue(); } },
                { "billContent", n => { BillContent = n.GetObjectValue<global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse_billContent>(global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse_billContent.CreateFromDiscriminatorValue); } },
                { "billingPeriodEndDate", n => { BillingPeriodEndDate = n.GetStringValue(); } },
                { "billingPeriodStartDate", n => { BillingPeriodStartDate = n.GetStringValue(); } },
                { "client", n => { Client = n.GetObjectValue<global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse_client>(global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse_client.CreateFromDiscriminatorValue); } },
                { "createTime", n => { CreateTime = n.GetStringValue(); } },
                { "currency", n => { Currency = n.GetStringValue(); } },
                { "deleted", n => { Deleted = n.GetBoolValue(); } },
                { "discount", n => { Discount = n.GetDoubleValue(); } },
                { "dueDate", n => { DueDate = n.GetStringValue(); } },
                { "errorDescription", n => { ErrorDescription = n.GetStringValue(); } },
                { "externalTax", n => { ExternalTax = n.GetObjectValue<global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse_externalTax>(global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse_externalTax.CreateFromDiscriminatorValue); } },
                { "failureReason", n => { FailureReason = n.GetStringValue(); } },
                { "hasActiveIntegrationData", n => { HasActiveIntegrationData = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "interval", n => { Interval = n.GetStringValue(); } },
                { "invoiceDate", n => { InvoiceDate = n.GetStringValue(); } },
                { "invoiceGenerationType", n => { InvoiceGenerationType = n.GetEnumValue<global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse_invoiceGenerationType>(); } },
                { "invoiceNote", n => { InvoiceNote = n.GetStringValue(); } },
                { "invoiceNumber", n => { InvoiceNumber = n.GetStringValue(); } },
                { "notes", n => { Notes = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "products", n => { Products = n.GetCollectionOfObjectValues<global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse_products>(global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse_products.CreateFromDiscriminatorValue)?.AsList(); } },
                { "status", n => { Status = n.GetEnumValue<global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse_status>(); } },
                { "subTotal", n => { SubTotal = n.GetDoubleValue(); } },
                { "subTotalWithDiscount", n => { SubTotalWithDiscount = n.GetDoubleValue(); } },
                { "taxRate", n => { TaxRate = n.GetDoubleValue(); } },
                { "ticketProducts", n => { TicketProducts = n.GetCollectionOfObjectValues<global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse_ticketProducts>(global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse_ticketProducts.CreateFromDiscriminatorValue)?.AsList(); } },
                { "total", n => { Total = n.GetDoubleValue(); } },
                { "totalTax", n => { TotalTax = n.GetDoubleValue(); } },
                { "updateTime", n => { UpdateTime = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse_agreement>("agreement", Agreement);
            writer.WriteCollectionOfObjectValues<global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse_agreementProducts>("agreementProducts", AgreementProducts);
            writer.WriteBoolValue("allowOnlineAchPayments", AllowOnlineAchPayments);
            writer.WriteBoolValue("allowOnlineCreditCardPayments", AllowOnlineCreditCardPayments);
            writer.WriteStringValue("appUserName", AppUserName);
            writer.WriteObjectValue<global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse_billContent>("billContent", BillContent);
            writer.WriteStringValue("billingPeriodEndDate", BillingPeriodEndDate);
            writer.WriteStringValue("billingPeriodStartDate", BillingPeriodStartDate);
            writer.WriteObjectValue<global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse_client>("client", Client);
            writer.WriteStringValue("createTime", CreateTime);
            writer.WriteStringValue("currency", Currency);
            writer.WriteBoolValue("deleted", Deleted);
            writer.WriteDoubleValue("discount", Discount);
            writer.WriteStringValue("dueDate", DueDate);
            writer.WriteStringValue("errorDescription", ErrorDescription);
            writer.WriteObjectValue<global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse_externalTax>("externalTax", ExternalTax);
            writer.WriteStringValue("failureReason", FailureReason);
            writer.WriteBoolValue("hasActiveIntegrationData", HasActiveIntegrationData);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("interval", Interval);
            writer.WriteStringValue("invoiceDate", InvoiceDate);
            writer.WriteEnumValue<global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse_invoiceGenerationType>("invoiceGenerationType", InvoiceGenerationType);
            writer.WriteStringValue("invoiceNote", InvoiceNote);
            writer.WriteStringValue("invoiceNumber", InvoiceNumber);
            writer.WriteCollectionOfPrimitiveValues<string>("notes", Notes);
            writer.WriteCollectionOfObjectValues<global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse_products>("products", Products);
            writer.WriteEnumValue<global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse_status>("status", Status);
            writer.WriteDoubleValue("subTotal", SubTotal);
            writer.WriteDoubleValue("subTotalWithDiscount", SubTotalWithDiscount);
            writer.WriteDoubleValue("taxRate", TaxRate);
            writer.WriteCollectionOfObjectValues<global::NinjaOne.Client.V2.Billing.Invoices.Item.InvoicesGetResponse_ticketProducts>("ticketProducts", TicketProducts);
            writer.WriteDoubleValue("total", Total);
            writer.WriteDoubleValue("totalTax", TotalTax);
            writer.WriteStringValue("updateTime", UpdateTime);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
