// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NinjaOne.Client.V2.Policies.Item.Condition.CustomFields
{
    /// <summary>Custom field operator</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CustomFieldsPostRequestBody_matchAny_operator
    {
        [EnumMember(Value = "EQUALS")]
        #pragma warning disable CS1591
        EQUALS,
        #pragma warning restore CS1591
        [EnumMember(Value = "NOT_EQUALS")]
        #pragma warning disable CS1591
        NOT_EQUALS,
        #pragma warning restore CS1591
        [EnumMember(Value = "LESS_THAN")]
        #pragma warning disable CS1591
        LESS_THAN,
        #pragma warning restore CS1591
        [EnumMember(Value = "LESS_OR_EQUAL_THAN")]
        #pragma warning disable CS1591
        LESS_OR_EQUAL_THAN,
        #pragma warning restore CS1591
        [EnumMember(Value = "GREATER_THAN")]
        #pragma warning disable CS1591
        GREATER_THAN,
        #pragma warning restore CS1591
        [EnumMember(Value = "GREATER_OR_EQUAL_THAN")]
        #pragma warning disable CS1591
        GREATER_OR_EQUAL_THAN,
        #pragma warning restore CS1591
        [EnumMember(Value = "IS_NOT_NULL")]
        #pragma warning disable CS1591
        IS_NOT_NULL,
        #pragma warning restore CS1591
        [EnumMember(Value = "CONTAINS")]
        #pragma warning disable CS1591
        CONTAINS,
        #pragma warning restore CS1591
        [EnumMember(Value = "CONTAINS_NONE")]
        #pragma warning disable CS1591
        CONTAINS_NONE,
        #pragma warning restore CS1591
        [EnumMember(Value = "CONTAINS_ANY")]
        #pragma warning disable CS1591
        CONTAINS_ANY,
        #pragma warning restore CS1591
    }
}
