// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.CustomFields.Item
{
    /// <summary>Policy condition script runAs</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WithCondition_5XXError_scripts_runAs
    {
        [EnumMember(Value = "SYSTEM")]
        #pragma warning disable CS1591
        SYSTEM,
        #pragma warning restore CS1591
        [EnumMember(Value = "LOGGED_ON_USER")]
        #pragma warning disable CS1591
        LOGGED_ON_USER,
        #pragma warning restore CS1591
        [EnumMember(Value = "LOCAL_ADMIN")]
        #pragma warning disable CS1591
        LOCAL_ADMIN,
        #pragma warning restore CS1591
        [EnumMember(Value = "DOMAIN_ADMIN")]
        #pragma warning disable CS1591
        DOMAIN_ADMIN,
        #pragma warning restore CS1591
        [EnumMember(Value = "PREFERRED_CREDENTIAL_MAC")]
        #pragma warning disable CS1591
        PREFERRED_CREDENTIAL_MAC,
        #pragma warning restore CS1591
        [EnumMember(Value = "PREFERRED_CREDENTIAL_LINUX")]
        #pragma warning disable CS1591
        PREFERRED_CREDENTIAL_LINUX,
        #pragma warning restore CS1591
    }
}
