// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NinjaOne.Client.NinjaRmm.V2.Ticketing.Ticket.Item.LogEntry
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetTypeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "DESCRIPTION")]
        #pragma warning disable CS1591
        DESCRIPTION,
        #pragma warning restore CS1591
        [EnumMember(Value = "COMMENT")]
        #pragma warning disable CS1591
        COMMENT,
        #pragma warning restore CS1591
        [EnumMember(Value = "CONDITION")]
        #pragma warning disable CS1591
        CONDITION,
        #pragma warning restore CS1591
        [EnumMember(Value = "SAVE")]
        #pragma warning disable CS1591
        SAVE,
        #pragma warning restore CS1591
        [EnumMember(Value = "DELETE")]
        #pragma warning disable CS1591
        DELETE,
        #pragma warning restore CS1591
        [EnumMember(Value = "PRODUCT")]
        #pragma warning disable CS1591
        PRODUCT,
        #pragma warning restore CS1591
    }
}
