// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using NinjaOne.Client.NinjaRmm.V2.Knowledgebase.Organization.Articles;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace NinjaOne.Client.NinjaRmm.V2.Knowledgebase.Organization
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\knowledgebase\organization
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OrganizationRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The articles property</summary>
        public global::NinjaOne.Client.NinjaRmm.V2.Knowledgebase.Organization.Articles.ArticlesRequestBuilder Articles
        {
            get => new global::NinjaOne.Client.NinjaRmm.V2.Knowledgebase.Organization.Articles.ArticlesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.NinjaRmm.V2.Knowledgebase.Organization.OrganizationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OrganizationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/knowledgebase/organization", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.NinjaRmm.V2.Knowledgebase.Organization.OrganizationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OrganizationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/knowledgebase/organization", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
