// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace NinjaOne.Client.NinjaRmm.V2.Device.Item.Scripting.Options
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Options4XXError : ApiException, IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The categories property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::NinjaOne.Client.NinjaRmm.V2.Device.Item.Scripting.Options.Options4XXError_categories>? Categories { get; set; }
#nullable restore
#else
        public List<global::NinjaOne.Client.NinjaRmm.V2.Device.Item.Scripting.Options.Options4XXError_categories> Categories { get; set; }
#endif
        /// <summary>The credentials property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.NinjaRmm.V2.Device.Item.Scripting.Options.Options4XXError_credentials? Credentials { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.NinjaRmm.V2.Device.Item.Scripting.Options.Options4XXError_credentials Credentials { get; set; }
#endif
        /// <summary>The primary error message.</summary>
        public override string Message { get => base.Message; }
        /// <summary>The scripts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::NinjaOne.Client.NinjaRmm.V2.Device.Item.Scripting.Options.Options4XXError_scripts>? Scripts { get; set; }
#nullable restore
#else
        public List<global::NinjaOne.Client.NinjaRmm.V2.Device.Item.Scripting.Options.Options4XXError_scripts> Scripts { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.NinjaRmm.V2.Device.Item.Scripting.Options.Options4XXError"/> and sets the default values.
        /// </summary>
        public Options4XXError()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NinjaOne.Client.NinjaRmm.V2.Device.Item.Scripting.Options.Options4XXError"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NinjaOne.Client.NinjaRmm.V2.Device.Item.Scripting.Options.Options4XXError CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::NinjaOne.Client.NinjaRmm.V2.Device.Item.Scripting.Options.Options4XXError();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "categories", n => { Categories = n.GetCollectionOfObjectValues<global::NinjaOne.Client.NinjaRmm.V2.Device.Item.Scripting.Options.Options4XXError_categories>(global::NinjaOne.Client.NinjaRmm.V2.Device.Item.Scripting.Options.Options4XXError_categories.CreateFromDiscriminatorValue)?.AsList(); } },
                { "credentials", n => { Credentials = n.GetObjectValue<global::NinjaOne.Client.NinjaRmm.V2.Device.Item.Scripting.Options.Options4XXError_credentials>(global::NinjaOne.Client.NinjaRmm.V2.Device.Item.Scripting.Options.Options4XXError_credentials.CreateFromDiscriminatorValue); } },
                { "scripts", n => { Scripts = n.GetCollectionOfObjectValues<global::NinjaOne.Client.NinjaRmm.V2.Device.Item.Scripting.Options.Options4XXError_scripts>(global::NinjaOne.Client.NinjaRmm.V2.Device.Item.Scripting.Options.Options4XXError_scripts.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::NinjaOne.Client.NinjaRmm.V2.Device.Item.Scripting.Options.Options4XXError_categories>("categories", Categories);
            writer.WriteObjectValue<global::NinjaOne.Client.NinjaRmm.V2.Device.Item.Scripting.Options.Options4XXError_credentials>("credentials", Credentials);
            writer.WriteCollectionOfObjectValues<global::NinjaOne.Client.NinjaRmm.V2.Device.Item.Scripting.Options.Options4XXError_scripts>("scripts", Scripts);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
