// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using NinjaOne.Client.V2.Ticketing.Ticket.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace NinjaOne.Client.V2.Ticketing.Ticket
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\ticketing\ticket
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TicketRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the NinjaOne.Client.v2.ticketing.ticket.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::NinjaOne.Client.V2.Ticketing.Ticket.Item.WithTicketItemRequestBuilder"/></returns>
        public global::NinjaOne.Client.V2.Ticketing.Ticket.Item.WithTicketItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("ticketId", position);
                return new global::NinjaOne.Client.V2.Ticketing.Ticket.Item.WithTicketItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.V2.Ticketing.Ticket.TicketRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TicketRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/ticketing/ticket", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.V2.Ticketing.Ticket.TicketRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TicketRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/ticketing/ticket", rawUrl)
        {
        }
        /// <summary>
        /// Create a new ticket, does not accept files
        /// </summary>
        /// <returns>A <see cref="global::NinjaOne.Client.V2.Ticketing.Ticket.TicketPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::NinjaOne.Client.V2.Ticketing.Ticket.TicketPostResponse?> PostAsync(global::NinjaOne.Client.V2.Ticketing.Ticket.TicketPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::NinjaOne.Client.V2.Ticketing.Ticket.TicketPostResponse> PostAsync(global::NinjaOne.Client.V2.Ticketing.Ticket.TicketPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::NinjaOne.Client.V2.Ticketing.Ticket.TicketPostResponse>(requestInfo, global::NinjaOne.Client.V2.Ticketing.Ticket.TicketPostResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Create a new ticket, does not accept files
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::NinjaOne.Client.V2.Ticketing.Ticket.TicketPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::NinjaOne.Client.V2.Ticketing.Ticket.TicketPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::NinjaOne.Client.V2.Ticketing.Ticket.TicketRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::NinjaOne.Client.V2.Ticketing.Ticket.TicketRequestBuilder WithUrl(string rawUrl)
        {
            return new global::NinjaOne.Client.V2.Ticketing.Ticket.TicketRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
