// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NinjaOne.Client.V2.Ticketing.TicketForm.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum TicketForm5XXError_fields_content_advancedSettings_identifier_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "CUSTOM")]
        #pragma warning disable CS1591
        CUSTOM,
        #pragma warning restore CS1591
        [EnumMember(Value = "SEQUENCE")]
        #pragma warning disable CS1591
        SEQUENCE,
        #pragma warning restore CS1591
    }
}
