// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NinjaOne.Client.NinjaRmm.V2.SoftwareLicense.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum WithLicensePutRequestBody_assigmentAutomationSettings_assignmentType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "NORMALIZED_SOFTWARE")]
        #pragma warning disable CS1591
        NORMALIZED_SOFTWARE,
        #pragma warning restore CS1591
        [EnumMember(Value = "SOFTWARE_INVENTORY")]
        #pragma warning disable CS1591
        SOFTWARE_INVENTORY,
        #pragma warning restore CS1591
        [EnumMember(Value = "DEVICE_SEARCH_GROUPS")]
        #pragma warning disable CS1591
        DEVICE_SEARCH_GROUPS,
        #pragma warning restore CS1591
        [EnumMember(Value = "END_USER_ROLES")]
        #pragma warning disable CS1591
        END_USER_ROLES,
        #pragma warning restore CS1591
    }
}
