// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NinjaOne.Client.V2.Queries.ScopedCustomFields
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ScopedCustomFieldsGetResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The cursor property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.Queries.ScopedCustomFields.ScopedCustomFieldsGetResponse_cursor? Cursor { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.Queries.ScopedCustomFields.ScopedCustomFieldsGetResponse_cursor Cursor { get; set; }
#endif
        /// <summary>The results property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::NinjaOne.Client.V2.Queries.ScopedCustomFields.ScopedCustomFieldsGetResponse_results>? Results { get; set; }
#nullable restore
#else
        public List<global::NinjaOne.Client.V2.Queries.ScopedCustomFields.ScopedCustomFieldsGetResponse_results> Results { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.V2.Queries.ScopedCustomFields.ScopedCustomFieldsGetResponse"/> and sets the default values.
        /// </summary>
        public ScopedCustomFieldsGetResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NinjaOne.Client.V2.Queries.ScopedCustomFields.ScopedCustomFieldsGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NinjaOne.Client.V2.Queries.ScopedCustomFields.ScopedCustomFieldsGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::NinjaOne.Client.V2.Queries.ScopedCustomFields.ScopedCustomFieldsGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cursor", n => { Cursor = n.GetObjectValue<global::NinjaOne.Client.V2.Queries.ScopedCustomFields.ScopedCustomFieldsGetResponse_cursor>(global::NinjaOne.Client.V2.Queries.ScopedCustomFields.ScopedCustomFieldsGetResponse_cursor.CreateFromDiscriminatorValue); } },
                { "results", n => { Results = n.GetCollectionOfObjectValues<global::NinjaOne.Client.V2.Queries.ScopedCustomFields.ScopedCustomFieldsGetResponse_results>(global::NinjaOne.Client.V2.Queries.ScopedCustomFields.ScopedCustomFieldsGetResponse_results.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::NinjaOne.Client.V2.Queries.ScopedCustomFields.ScopedCustomFieldsGetResponse_cursor>("cursor", Cursor);
            writer.WriteCollectionOfObjectValues<global::NinjaOne.Client.V2.Queries.ScopedCustomFields.ScopedCustomFieldsGetResponse_results>("results", Results);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
