// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.Relation
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RelationPostResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The identifier of the user who created the related item</summary>
        public int? CreatedByAppUserId { get; set; }
        /// <summary>Creation time</summary>
        public double? CreateTime { get; set; }
        /// <summary>Entity</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.Relation.RelationPostResponse_entity? Entity { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.Relation.RelationPostResponse_entity Entity { get; set; }
#endif
        /// <summary>Entity Identifier</summary>
        public int? EntityId { get; set; }
        /// <summary>Entity Type</summary>
        public global::NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.Relation.RelationPostResponse_entityType? EntityType { get; set; }
        /// <summary>Identifier</summary>
        public int? Id { get; set; }
        /// <summary>Related Entity</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.Relation.RelationPostResponse_relEntity? RelEntity { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.Relation.RelationPostResponse_relEntity RelEntity { get; set; }
#endif
        /// <summary>Related Entity Identifier</summary>
        public int? RelEntityId { get; set; }
        /// <summary>Related Entity Type</summary>
        public global::NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.Relation.RelationPostResponse_relEntityType? RelEntityType { get; set; }
        /// <summary>Type of Relation</summary>
        public global::NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.Relation.RelationPostResponse_type? Type { get; set; }
        /// <summary>The identifier of the last user to update the related item</summary>
        public int? UpdatedByAppUserId { get; set; }
        /// <summary>Last update time</summary>
        public double? UpdateTime { get; set; }
        /// <summary>Related item value (Attachment meta data / Secure information)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.Relation.RelationPostResponse_value? Value { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.Relation.RelationPostResponse_value Value { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.Relation.RelationPostResponse"/> and sets the default values.
        /// </summary>
        public RelationPostResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.Relation.RelationPostResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.Relation.RelationPostResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.Relation.RelationPostResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createTime", n => { CreateTime = n.GetDoubleValue(); } },
                { "createdByAppUserId", n => { CreatedByAppUserId = n.GetIntValue(); } },
                { "entity", n => { Entity = n.GetObjectValue<global::NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.Relation.RelationPostResponse_entity>(global::NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.Relation.RelationPostResponse_entity.CreateFromDiscriminatorValue); } },
                { "entityId", n => { EntityId = n.GetIntValue(); } },
                { "entityType", n => { EntityType = n.GetEnumValue<global::NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.Relation.RelationPostResponse_entityType>(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "relEntity", n => { RelEntity = n.GetObjectValue<global::NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.Relation.RelationPostResponse_relEntity>(global::NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.Relation.RelationPostResponse_relEntity.CreateFromDiscriminatorValue); } },
                { "relEntityId", n => { RelEntityId = n.GetIntValue(); } },
                { "relEntityType", n => { RelEntityType = n.GetEnumValue<global::NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.Relation.RelationPostResponse_relEntityType>(); } },
                { "type", n => { Type = n.GetEnumValue<global::NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.Relation.RelationPostResponse_type>(); } },
                { "updateTime", n => { UpdateTime = n.GetDoubleValue(); } },
                { "updatedByAppUserId", n => { UpdatedByAppUserId = n.GetIntValue(); } },
                { "value", n => { Value = n.GetObjectValue<global::NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.Relation.RelationPostResponse_value>(global::NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.Relation.RelationPostResponse_value.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("createdByAppUserId", CreatedByAppUserId);
            writer.WriteDoubleValue("createTime", CreateTime);
            writer.WriteObjectValue<global::NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.Relation.RelationPostResponse_entity>("entity", Entity);
            writer.WriteIntValue("entityId", EntityId);
            writer.WriteEnumValue<global::NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.Relation.RelationPostResponse_entityType>("entityType", EntityType);
            writer.WriteIntValue("id", Id);
            writer.WriteObjectValue<global::NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.Relation.RelationPostResponse_relEntity>("relEntity", RelEntity);
            writer.WriteIntValue("relEntityId", RelEntityId);
            writer.WriteEnumValue<global::NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.Relation.RelationPostResponse_relEntityType>("relEntityType", RelEntityType);
            writer.WriteEnumValue<global::NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.Relation.RelationPostResponse_type>("type", Type);
            writer.WriteIntValue("updatedByAppUserId", UpdatedByAppUserId);
            writer.WriteDoubleValue("updateTime", UpdateTime);
            writer.WriteObjectValue<global::NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.Relation.RelationPostResponse_value>("value", Value);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
