// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NinjaOne.Client.NinjaRmm.V2.Ticketing.Ticket.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithTicketPutRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Additional assigned technician identifiers</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? AdditionalAssignedTechnicianIds { get; set; }
#nullable restore
#else
        public List<int?> AdditionalAssignedTechnicianIds { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The assignedAppUserId property</summary>
        public int? AssignedAppUserId { get; set; }
        /// <summary>The attributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::NinjaOne.Client.NinjaRmm.V2.Ticketing.Ticket.Item.WithTicketPutRequestBody_attributes>? Attributes { get; set; }
#nullable restore
#else
        public List<global::NinjaOne.Client.NinjaRmm.V2.Ticketing.Ticket.Item.WithTicketPutRequestBody_attributes> Attributes { get; set; }
#endif
        /// <summary>The cc property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.NinjaRmm.V2.Ticketing.Ticket.Item.WithTicketPutRequestBody_cc? Cc { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.NinjaRmm.V2.Ticketing.Ticket.Item.WithTicketPutRequestBody_cc Cc { get; set; }
#endif
        /// <summary>Client (Organization) identifier</summary>
        public int? ClientId { get; set; }
        /// <summary>Follow-up time for the ticket in epoch seconds</summary>
        public double? FollowupTime { get; set; }
        /// <summary>Location identifier</summary>
        public int? LocationId { get; set; }
        /// <summary>Device identifier</summary>
        public int? NodeId { get; set; }
        /// <summary>Ticket parent identifier</summary>
        public int? ParentTicketId { get; set; }
        /// <summary>The priority property</summary>
        public global::NinjaOne.Client.NinjaRmm.V2.Ticketing.Ticket.Item.WithTicketPutRequestBody_priority? Priority { get; set; }
        /// <summary>The requesterUid property</summary>
        public Guid? RequesterUid { get; set; }
        /// <summary>The severity property</summary>
        public global::NinjaOne.Client.NinjaRmm.V2.Ticketing.Ticket.Item.WithTicketPutRequestBody_severity? Severity { get; set; }
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The subject property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject { get; set; }
#nullable restore
#else
        public string Subject { get; set; }
#endif
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tags { get; set; }
#nullable restore
#else
        public List<string> Tags { get; set; }
#endif
        /// <summary>Ticket form identifier</summary>
        public int? TicketFormId { get; set; }
        /// <summary>Type of ticket</summary>
        public global::NinjaOne.Client.NinjaRmm.V2.Ticketing.Ticket.Item.WithTicketPutRequestBody_type? Type { get; set; }
        /// <summary>ticket version</summary>
        public int? Version { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.NinjaRmm.V2.Ticketing.Ticket.Item.WithTicketPutRequestBody"/> and sets the default values.
        /// </summary>
        public WithTicketPutRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
            Priority = global::NinjaOne.Client.NinjaRmm.V2.Ticketing.Ticket.Item.WithTicketPutRequestBody_priority.NONE;
            Severity = global::NinjaOne.Client.NinjaRmm.V2.Ticketing.Ticket.Item.WithTicketPutRequestBody_severity.NONE;
            Status = "1000";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NinjaOne.Client.NinjaRmm.V2.Ticketing.Ticket.Item.WithTicketPutRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NinjaOne.Client.NinjaRmm.V2.Ticketing.Ticket.Item.WithTicketPutRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::NinjaOne.Client.NinjaRmm.V2.Ticketing.Ticket.Item.WithTicketPutRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "additionalAssignedTechnicianIds", n => { AdditionalAssignedTechnicianIds = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "assignedAppUserId", n => { AssignedAppUserId = n.GetIntValue(); } },
                { "attributes", n => { Attributes = n.GetCollectionOfObjectValues<global::NinjaOne.Client.NinjaRmm.V2.Ticketing.Ticket.Item.WithTicketPutRequestBody_attributes>(global::NinjaOne.Client.NinjaRmm.V2.Ticketing.Ticket.Item.WithTicketPutRequestBody_attributes.CreateFromDiscriminatorValue)?.AsList(); } },
                { "cc", n => { Cc = n.GetObjectValue<global::NinjaOne.Client.NinjaRmm.V2.Ticketing.Ticket.Item.WithTicketPutRequestBody_cc>(global::NinjaOne.Client.NinjaRmm.V2.Ticketing.Ticket.Item.WithTicketPutRequestBody_cc.CreateFromDiscriminatorValue); } },
                { "clientId", n => { ClientId = n.GetIntValue(); } },
                { "followupTime", n => { FollowupTime = n.GetDoubleValue(); } },
                { "locationId", n => { LocationId = n.GetIntValue(); } },
                { "nodeId", n => { NodeId = n.GetIntValue(); } },
                { "parentTicketId", n => { ParentTicketId = n.GetIntValue(); } },
                { "priority", n => { Priority = n.GetEnumValue<global::NinjaOne.Client.NinjaRmm.V2.Ticketing.Ticket.Item.WithTicketPutRequestBody_priority>(); } },
                { "requesterUid", n => { RequesterUid = n.GetGuidValue(); } },
                { "severity", n => { Severity = n.GetEnumValue<global::NinjaOne.Client.NinjaRmm.V2.Ticketing.Ticket.Item.WithTicketPutRequestBody_severity>(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "subject", n => { Subject = n.GetStringValue(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "ticketFormId", n => { TicketFormId = n.GetIntValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::NinjaOne.Client.NinjaRmm.V2.Ticketing.Ticket.Item.WithTicketPutRequestBody_type>(); } },
                { "version", n => { Version = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<int?>("additionalAssignedTechnicianIds", AdditionalAssignedTechnicianIds);
            writer.WriteIntValue("assignedAppUserId", AssignedAppUserId);
            writer.WriteCollectionOfObjectValues<global::NinjaOne.Client.NinjaRmm.V2.Ticketing.Ticket.Item.WithTicketPutRequestBody_attributes>("attributes", Attributes);
            writer.WriteObjectValue<global::NinjaOne.Client.NinjaRmm.V2.Ticketing.Ticket.Item.WithTicketPutRequestBody_cc>("cc", Cc);
            writer.WriteIntValue("clientId", ClientId);
            writer.WriteDoubleValue("followupTime", FollowupTime);
            writer.WriteIntValue("locationId", LocationId);
            writer.WriteIntValue("nodeId", NodeId);
            writer.WriteIntValue("parentTicketId", ParentTicketId);
            writer.WriteEnumValue<global::NinjaOne.Client.NinjaRmm.V2.Ticketing.Ticket.Item.WithTicketPutRequestBody_priority>("priority", Priority);
            writer.WriteGuidValue("requesterUid", RequesterUid);
            writer.WriteEnumValue<global::NinjaOne.Client.NinjaRmm.V2.Ticketing.Ticket.Item.WithTicketPutRequestBody_severity>("severity", Severity);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("subject", Subject);
            writer.WriteCollectionOfPrimitiveValues<string>("tags", Tags);
            writer.WriteIntValue("ticketFormId", TicketFormId);
            writer.WriteEnumValue<global::NinjaOne.Client.NinjaRmm.V2.Ticketing.Ticket.Item.WithTicketPutRequestBody_type>("type", Type);
            writer.WriteIntValue("version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
