// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NinjaOne.Client.NinjaRmm.V2.Tag.Merge
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MergePostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>If creating a new tag, you can supply the new tag description here</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>If merging into an existing tag, you must provide the target tag id here</summary>
        public int? MergeIntoTagId { get; set; }
        /// <summary>Method to use - merge into an existing tag or create a new one</summary>
        public global::NinjaOne.Client.NinjaRmm.V2.Tag.Merge.MergePostRequestBody_mergeMethod? MergeMethod { get; set; }
        /// <summary>If creating a new tag, you must supply the new tag name here</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Array of tag ids to merge</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? TagIds { get; set; }
#nullable restore
#else
        public List<int?> TagIds { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.NinjaRmm.V2.Tag.Merge.MergePostRequestBody"/> and sets the default values.
        /// </summary>
        public MergePostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NinjaOne.Client.NinjaRmm.V2.Tag.Merge.MergePostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NinjaOne.Client.NinjaRmm.V2.Tag.Merge.MergePostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::NinjaOne.Client.NinjaRmm.V2.Tag.Merge.MergePostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "description", n => { Description = n.GetStringValue(); } },
                { "mergeIntoTagId", n => { MergeIntoTagId = n.GetIntValue(); } },
                { "mergeMethod", n => { MergeMethod = n.GetEnumValue<global::NinjaOne.Client.NinjaRmm.V2.Tag.Merge.MergePostRequestBody_mergeMethod>(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "tagIds", n => { TagIds = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("description", Description);
            writer.WriteIntValue("mergeIntoTagId", MergeIntoTagId);
            writer.WriteEnumValue<global::NinjaOne.Client.NinjaRmm.V2.Tag.Merge.MergePostRequestBody_mergeMethod>("mergeMethod", MergeMethod);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfPrimitiveValues<int?>("tagIds", TagIds);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
