// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using NinjaOne.Client.NinjaRmm.V2.Itam.UnmanagedDevice.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace NinjaOne.Client.NinjaRmm.V2.Itam.UnmanagedDevice
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\itam\unmanaged-device
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UnmanagedDeviceRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the NinjaOne.Client.NinjaRmm.v2.itam.unmanagedDevice.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::NinjaOne.Client.NinjaRmm.V2.Itam.UnmanagedDevice.Item.WithNodeItemRequestBuilder"/></returns>
        public global::NinjaOne.Client.NinjaRmm.V2.Itam.UnmanagedDevice.Item.WithNodeItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("nodeId", position);
                return new global::NinjaOne.Client.NinjaRmm.V2.Itam.UnmanagedDevice.Item.WithNodeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the NinjaOne.Client.NinjaRmm.v2.itam.unmanagedDevice.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::NinjaOne.Client.NinjaRmm.V2.Itam.UnmanagedDevice.Item.WithNodeItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::NinjaOne.Client.NinjaRmm.V2.Itam.UnmanagedDevice.Item.WithNodeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("nodeId", position);
                return new global::NinjaOne.Client.NinjaRmm.V2.Itam.UnmanagedDevice.Item.WithNodeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.NinjaRmm.V2.Itam.UnmanagedDevice.UnmanagedDeviceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UnmanagedDeviceRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/itam/unmanaged-device", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.NinjaRmm.V2.Itam.UnmanagedDevice.UnmanagedDeviceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UnmanagedDeviceRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/itam/unmanaged-device", rawUrl)
        {
        }
        /// <summary>
        /// Create an Unmanaged Device with the provided details
        /// </summary>
        /// <returns>A <see cref="global::NinjaOne.Client.NinjaRmm.V2.Itam.UnmanagedDevice.UnmanagedDevicePostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::NinjaOne.Client.NinjaRmm.V2.Itam.UnmanagedDevice.UnmanagedDevicePostResponse?> PostAsUnmanagedDevicePostResponseAsync(global::NinjaOne.Client.NinjaRmm.V2.Itam.UnmanagedDevice.UnmanagedDevicePostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::NinjaOne.Client.NinjaRmm.V2.Itam.UnmanagedDevice.UnmanagedDevicePostResponse> PostAsUnmanagedDevicePostResponseAsync(global::NinjaOne.Client.NinjaRmm.V2.Itam.UnmanagedDevice.UnmanagedDevicePostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::NinjaOne.Client.NinjaRmm.V2.Itam.UnmanagedDevice.UnmanagedDevicePostResponse>(requestInfo, global::NinjaOne.Client.NinjaRmm.V2.Itam.UnmanagedDevice.UnmanagedDevicePostResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Create an Unmanaged Device with the provided details
        /// </summary>
        /// <returns>A <see cref="global::NinjaOne.Client.NinjaRmm.V2.Itam.UnmanagedDevice.UnmanagedDeviceResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use PostAsUnmanagedDevicePostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::NinjaOne.Client.NinjaRmm.V2.Itam.UnmanagedDevice.UnmanagedDeviceResponse?> PostAsync(global::NinjaOne.Client.NinjaRmm.V2.Itam.UnmanagedDevice.UnmanagedDevicePostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::NinjaOne.Client.NinjaRmm.V2.Itam.UnmanagedDevice.UnmanagedDeviceResponse> PostAsync(global::NinjaOne.Client.NinjaRmm.V2.Itam.UnmanagedDevice.UnmanagedDevicePostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::NinjaOne.Client.NinjaRmm.V2.Itam.UnmanagedDevice.UnmanagedDeviceResponse>(requestInfo, global::NinjaOne.Client.NinjaRmm.V2.Itam.UnmanagedDevice.UnmanagedDeviceResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Create an Unmanaged Device with the provided details
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::NinjaOne.Client.NinjaRmm.V2.Itam.UnmanagedDevice.UnmanagedDevicePostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::NinjaOne.Client.NinjaRmm.V2.Itam.UnmanagedDevice.UnmanagedDevicePostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::NinjaOne.Client.NinjaRmm.V2.Itam.UnmanagedDevice.UnmanagedDeviceRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::NinjaOne.Client.NinjaRmm.V2.Itam.UnmanagedDevice.UnmanagedDeviceRequestBuilder WithUrl(string rawUrl)
        {
            return new global::NinjaOne.Client.NinjaRmm.V2.Itam.UnmanagedDevice.UnmanagedDeviceRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UnmanagedDeviceRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
