// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using NinjaOne.Client.NinjaRmm.V2.Tab.Summary.EndUser;
using NinjaOne.Client.NinjaRmm.V2.Tab.Summary.Organization;
using NinjaOne.Client.NinjaRmm.V2.Tab.Summary.Role;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace NinjaOne.Client.NinjaRmm.V2.Tab.Summary
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\tab\summary
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SummaryRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The endUser property</summary>
        public global::NinjaOne.Client.NinjaRmm.V2.Tab.Summary.EndUser.EndUserRequestBuilder EndUser
        {
            get => new global::NinjaOne.Client.NinjaRmm.V2.Tab.Summary.EndUser.EndUserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The organization property</summary>
        public global::NinjaOne.Client.NinjaRmm.V2.Tab.Summary.Organization.OrganizationRequestBuilder Organization
        {
            get => new global::NinjaOne.Client.NinjaRmm.V2.Tab.Summary.Organization.OrganizationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The role property</summary>
        public global::NinjaOne.Client.NinjaRmm.V2.Tab.Summary.Role.RoleRequestBuilder Role
        {
            get => new global::NinjaOne.Client.NinjaRmm.V2.Tab.Summary.Role.RoleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.NinjaRmm.V2.Tab.Summary.SummaryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SummaryRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/tab/summary", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.NinjaRmm.V2.Tab.Summary.SummaryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SummaryRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/tab/summary", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
