// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NinjaOne.Client.NinjaRmm.V2.Tab.Item
{
    /// <summary>The type of object the tab is for (ie, NODE_ROLE, ORGANIZATION, END_USER, etc)</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WithTabGetResponse_entityType
    {
        [EnumMember(Value = "NODE_ROLE")]
        #pragma warning disable CS1591
        NODE_ROLE,
        #pragma warning restore CS1591
        [EnumMember(Value = "ORGANIZATION")]
        #pragma warning disable CS1591
        ORGANIZATION,
        #pragma warning restore CS1591
        [EnumMember(Value = "END_USER")]
        #pragma warning disable CS1591
        END_USER,
        #pragma warning restore CS1591
        [EnumMember(Value = "SYSTEM")]
        #pragma warning disable CS1591
        SYSTEM,
        #pragma warning restore CS1591
    }
}
