// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NinjaOne.Client.NinjaRmm.V2.Tab
{
    /// <summary>
    /// This object represents either an attribute, or a UI Element. The available attributes will depend on which type it is
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TabPostResponse_items : IAdditionalDataHolder, IParsable
    {
        /// <summary>Whether the attribute is active or not</summary>
        public bool? Active { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Type of API permission on the attribute</summary>
        public global::NinjaOne.Client.NinjaRmm.V2.Tab.TabPostResponse_items_apiPermission? ApiPermission { get; set; }
        /// <summary>Scope of the attribute. NOTE: This field is being depricated</summary>
        public global::NinjaOne.Client.NinjaRmm.V2.Tab.TabPostResponse_items_attributeScope? AttributeScope { get; set; }
        /// <summary>Type of the attribute</summary>
        public global::NinjaOne.Client.NinjaRmm.V2.Tab.TabPostResponse_items_attributeType? AttributeType { get; set; }
        /// <summary>For multi-select attributes, these are the available content options</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.NinjaRmm.V2.Tab.TabPostResponse_items_content? Content { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.NinjaRmm.V2.Tab.TabPostResponse_items_content Content { get; set; }
#endif
        /// <summary>The time that the attribute was created (unix epoch)</summary>
        public double? CreateTime { get; set; }
        /// <summary>For multi-select attributes, this is the id of the default value</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultValue { get; set; }
#nullable restore
#else
        public string DefaultValue { get; set; }
#endif
        /// <summary>Definition scopes of the attribute</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::NinjaOne.Client.NinjaRmm.V2.Tab.TabPostResponse_items_definitionScope?>? DefinitionScope { get; set; }
#nullable restore
#else
        public List<global::NinjaOne.Client.NinjaRmm.V2.Tab.TabPostResponse_items_definitionScope?> DefinitionScope { get; set; }
#endif
        /// <summary>Description of the content item</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>If the attribute references a specific entity, its type will be specified in this field</summary>
        public global::NinjaOne.Client.NinjaRmm.V2.Tab.TabPostResponse_items_entityType? EntityType { get; set; }
        /// <summary>Field name of the attribute</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FieldName { get; set; }
#nullable restore
#else
        public string FieldName { get; set; }
#endif
        /// <summary>ID of an attribute</summary>
        public int? Id { get; set; }
        /// <summary>Name of the content item</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Type of script permission on the attribute</summary>
        public global::NinjaOne.Client.NinjaRmm.V2.Tab.TabPostResponse_items_scriptPermission? ScriptPermission { get; set; }
        /// <summary>Type of technician permission on the attribute</summary>
        public global::NinjaOne.Client.NinjaRmm.V2.Tab.TabPostResponse_items_technicianPermission? TechnicianPermission { get; set; }
        /// <summary>For UI elements, timestamp of when the element was created (unix epoch)</summary>
        public double? UiElementCreateTime { get; set; }
        /// <summary>For UI elements, type of the element</summary>
        public global::NinjaOne.Client.NinjaRmm.V2.Tab.TabPostResponse_items_uiElementType? UiElementType { get; set; }
        /// <summary>For UI elements, the uuid of the element</summary>
        public Guid? UiElementUid { get; set; }
        /// <summary>For UI elements, timestamp of when the element was last updated (unix epoch)</summary>
        public double? UiElementUpdateTime { get; set; }
        /// <summary>For UI elements, value of the element</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UiElementValue { get; set; }
#nullable restore
#else
        public string UiElementValue { get; set; }
#endif
        /// <summary>The time that the attribute was last updated (unix epoch)</summary>
        public double? UpdateTime { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.NinjaRmm.V2.Tab.TabPostResponse_items"/> and sets the default values.
        /// </summary>
        public TabPostResponse_items()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NinjaOne.Client.NinjaRmm.V2.Tab.TabPostResponse_items"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NinjaOne.Client.NinjaRmm.V2.Tab.TabPostResponse_items CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::NinjaOne.Client.NinjaRmm.V2.Tab.TabPostResponse_items();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "active", n => { Active = n.GetBoolValue(); } },
                { "apiPermission", n => { ApiPermission = n.GetEnumValue<global::NinjaOne.Client.NinjaRmm.V2.Tab.TabPostResponse_items_apiPermission>(); } },
                { "attributeScope", n => { AttributeScope = n.GetEnumValue<global::NinjaOne.Client.NinjaRmm.V2.Tab.TabPostResponse_items_attributeScope>(); } },
                { "attributeType", n => { AttributeType = n.GetEnumValue<global::NinjaOne.Client.NinjaRmm.V2.Tab.TabPostResponse_items_attributeType>(); } },
                { "content", n => { Content = n.GetObjectValue<global::NinjaOne.Client.NinjaRmm.V2.Tab.TabPostResponse_items_content>(global::NinjaOne.Client.NinjaRmm.V2.Tab.TabPostResponse_items_content.CreateFromDiscriminatorValue); } },
                { "createTime", n => { CreateTime = n.GetDoubleValue(); } },
                { "defaultValue", n => { DefaultValue = n.GetStringValue(); } },
                { "definitionScope", n => { DefinitionScope = n.GetCollectionOfEnumValues<global::NinjaOne.Client.NinjaRmm.V2.Tab.TabPostResponse_items_definitionScope>()?.AsList(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "entityType", n => { EntityType = n.GetEnumValue<global::NinjaOne.Client.NinjaRmm.V2.Tab.TabPostResponse_items_entityType>(); } },
                { "fieldName", n => { FieldName = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "scriptPermission", n => { ScriptPermission = n.GetEnumValue<global::NinjaOne.Client.NinjaRmm.V2.Tab.TabPostResponse_items_scriptPermission>(); } },
                { "technicianPermission", n => { TechnicianPermission = n.GetEnumValue<global::NinjaOne.Client.NinjaRmm.V2.Tab.TabPostResponse_items_technicianPermission>(); } },
                { "uiElementCreateTime", n => { UiElementCreateTime = n.GetDoubleValue(); } },
                { "uiElementType", n => { UiElementType = n.GetEnumValue<global::NinjaOne.Client.NinjaRmm.V2.Tab.TabPostResponse_items_uiElementType>(); } },
                { "uiElementUid", n => { UiElementUid = n.GetGuidValue(); } },
                { "uiElementUpdateTime", n => { UiElementUpdateTime = n.GetDoubleValue(); } },
                { "uiElementValue", n => { UiElementValue = n.GetStringValue(); } },
                { "updateTime", n => { UpdateTime = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("active", Active);
            writer.WriteEnumValue<global::NinjaOne.Client.NinjaRmm.V2.Tab.TabPostResponse_items_apiPermission>("apiPermission", ApiPermission);
            writer.WriteEnumValue<global::NinjaOne.Client.NinjaRmm.V2.Tab.TabPostResponse_items_attributeScope>("attributeScope", AttributeScope);
            writer.WriteEnumValue<global::NinjaOne.Client.NinjaRmm.V2.Tab.TabPostResponse_items_attributeType>("attributeType", AttributeType);
            writer.WriteObjectValue<global::NinjaOne.Client.NinjaRmm.V2.Tab.TabPostResponse_items_content>("content", Content);
            writer.WriteDoubleValue("createTime", CreateTime);
            writer.WriteStringValue("defaultValue", DefaultValue);
            writer.WriteCollectionOfEnumValues<global::NinjaOne.Client.NinjaRmm.V2.Tab.TabPostResponse_items_definitionScope>("definitionScope", DefinitionScope);
            writer.WriteStringValue("description", Description);
            writer.WriteEnumValue<global::NinjaOne.Client.NinjaRmm.V2.Tab.TabPostResponse_items_entityType>("entityType", EntityType);
            writer.WriteStringValue("fieldName", FieldName);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::NinjaOne.Client.NinjaRmm.V2.Tab.TabPostResponse_items_scriptPermission>("scriptPermission", ScriptPermission);
            writer.WriteEnumValue<global::NinjaOne.Client.NinjaRmm.V2.Tab.TabPostResponse_items_technicianPermission>("technicianPermission", TechnicianPermission);
            writer.WriteDoubleValue("uiElementCreateTime", UiElementCreateTime);
            writer.WriteEnumValue<global::NinjaOne.Client.NinjaRmm.V2.Tab.TabPostResponse_items_uiElementType>("uiElementType", UiElementType);
            writer.WriteGuidValue("uiElementUid", UiElementUid);
            writer.WriteDoubleValue("uiElementUpdateTime", UiElementUpdateTime);
            writer.WriteStringValue("uiElementValue", UiElementValue);
            writer.WriteDoubleValue("updateTime", UpdateTime);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
