// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace NinjaOne.Client.V2.DeviceCustomFields
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DeviceCustomFields : ApiException, IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Active</summary>
        public bool? Active { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Public API Permission</summary>
        public global::NinjaOne.Client.V2.DeviceCustomFields.DeviceCustomFields_apiPermission? ApiPermission { get; set; }
        /// <summary>The content property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.DeviceCustomFields.DeviceCustomFields_content? Content { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.DeviceCustomFields.DeviceCustomFields_content Content { get; set; }
#endif
        /// <summary>Create Time</summary>
        public double? CreateTime { get; set; }
        /// <summary>Default Value</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultValue { get; set; }
#nullable restore
#else
        public string DefaultValue { get; set; }
#endif
        /// <summary>Definition Scope</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::NinjaOne.Client.V2.DeviceCustomFields.DeviceCustomFields_definitionScope?>? DefinitionScope { get; set; }
#nullable restore
#else
        public List<global::NinjaOne.Client.V2.DeviceCustomFields.DeviceCustomFields_definitionScope?> DefinitionScope { get; set; }
#endif
        /// <summary>Description</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>End User Permission</summary>
        public global::NinjaOne.Client.V2.DeviceCustomFields.DeviceCustomFields_endUserPermission? EndUserPermission { get; set; }
        /// <summary>Entity Type</summary>
        public global::NinjaOne.Client.V2.DeviceCustomFields.DeviceCustomFields_entityType? EntityType { get; set; }
        /// <summary>Label</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Label { get; set; }
#nullable restore
#else
        public string Label { get; set; }
#endif
        /// <summary>The primary error message.</summary>
        public override string Message { get => base.Message; }
        /// <summary>Name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Scope</summary>
        public global::NinjaOne.Client.V2.DeviceCustomFields.DeviceCustomFields_scope? Scope { get; set; }
        /// <summary>Script Permission</summary>
        public global::NinjaOne.Client.V2.DeviceCustomFields.DeviceCustomFields_scriptPermission? ScriptPermission { get; set; }
        /// <summary>System</summary>
        public bool? System { get; set; }
        /// <summary>Technician Permission</summary>
        public global::NinjaOne.Client.V2.DeviceCustomFields.DeviceCustomFields_technicianPermission? TechnicianPermission { get; set; }
        /// <summary>Type</summary>
        public global::NinjaOne.Client.V2.DeviceCustomFields.DeviceCustomFields_type? Type { get; set; }
        /// <summary>Update Time</summary>
        public double? UpdateTime { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.V2.DeviceCustomFields.DeviceCustomFields"/> and sets the default values.
        /// </summary>
        public DeviceCustomFields()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NinjaOne.Client.V2.DeviceCustomFields.DeviceCustomFields"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NinjaOne.Client.V2.DeviceCustomFields.DeviceCustomFields CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::NinjaOne.Client.V2.DeviceCustomFields.DeviceCustomFields();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "active", n => { Active = n.GetBoolValue(); } },
                { "apiPermission", n => { ApiPermission = n.GetEnumValue<global::NinjaOne.Client.V2.DeviceCustomFields.DeviceCustomFields_apiPermission>(); } },
                { "content", n => { Content = n.GetObjectValue<global::NinjaOne.Client.V2.DeviceCustomFields.DeviceCustomFields_content>(global::NinjaOne.Client.V2.DeviceCustomFields.DeviceCustomFields_content.CreateFromDiscriminatorValue); } },
                { "createTime", n => { CreateTime = n.GetDoubleValue(); } },
                { "defaultValue", n => { DefaultValue = n.GetStringValue(); } },
                { "definitionScope", n => { DefinitionScope = n.GetCollectionOfEnumValues<global::NinjaOne.Client.V2.DeviceCustomFields.DeviceCustomFields_definitionScope>()?.AsList(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "endUserPermission", n => { EndUserPermission = n.GetEnumValue<global::NinjaOne.Client.V2.DeviceCustomFields.DeviceCustomFields_endUserPermission>(); } },
                { "entityType", n => { EntityType = n.GetEnumValue<global::NinjaOne.Client.V2.DeviceCustomFields.DeviceCustomFields_entityType>(); } },
                { "label", n => { Label = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "scope", n => { Scope = n.GetEnumValue<global::NinjaOne.Client.V2.DeviceCustomFields.DeviceCustomFields_scope>(); } },
                { "scriptPermission", n => { ScriptPermission = n.GetEnumValue<global::NinjaOne.Client.V2.DeviceCustomFields.DeviceCustomFields_scriptPermission>(); } },
                { "system", n => { System = n.GetBoolValue(); } },
                { "technicianPermission", n => { TechnicianPermission = n.GetEnumValue<global::NinjaOne.Client.V2.DeviceCustomFields.DeviceCustomFields_technicianPermission>(); } },
                { "type", n => { Type = n.GetEnumValue<global::NinjaOne.Client.V2.DeviceCustomFields.DeviceCustomFields_type>(); } },
                { "updateTime", n => { UpdateTime = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("active", Active);
            writer.WriteEnumValue<global::NinjaOne.Client.V2.DeviceCustomFields.DeviceCustomFields_apiPermission>("apiPermission", ApiPermission);
            writer.WriteObjectValue<global::NinjaOne.Client.V2.DeviceCustomFields.DeviceCustomFields_content>("content", Content);
            writer.WriteDoubleValue("createTime", CreateTime);
            writer.WriteStringValue("defaultValue", DefaultValue);
            writer.WriteCollectionOfEnumValues<global::NinjaOne.Client.V2.DeviceCustomFields.DeviceCustomFields_definitionScope>("definitionScope", DefinitionScope);
            writer.WriteStringValue("description", Description);
            writer.WriteEnumValue<global::NinjaOne.Client.V2.DeviceCustomFields.DeviceCustomFields_endUserPermission>("endUserPermission", EndUserPermission);
            writer.WriteEnumValue<global::NinjaOne.Client.V2.DeviceCustomFields.DeviceCustomFields_entityType>("entityType", EntityType);
            writer.WriteStringValue("label", Label);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::NinjaOne.Client.V2.DeviceCustomFields.DeviceCustomFields_scope>("scope", Scope);
            writer.WriteEnumValue<global::NinjaOne.Client.V2.DeviceCustomFields.DeviceCustomFields_scriptPermission>("scriptPermission", ScriptPermission);
            writer.WriteBoolValue("system", System);
            writer.WriteEnumValue<global::NinjaOne.Client.V2.DeviceCustomFields.DeviceCustomFields_technicianPermission>("technicianPermission", TechnicianPermission);
            writer.WriteEnumValue<global::NinjaOne.Client.V2.DeviceCustomFields.DeviceCustomFields_type>("type", Type);
            writer.WriteDoubleValue("updateTime", UpdateTime);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
