// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NinjaOne.Client.V2.Billing.Agreements
{
    /// <summary>
    /// Representation of a ninja billing Agreement.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AgreementsPostResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>The active property</summary>
        public bool? Active { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The allowOnlineAchPayments property</summary>
        public bool? AllowOnlineAchPayments { get; set; }
        /// <summary>The allowOnlineCreditCardPayments property</summary>
        public bool? AllowOnlineCreditCardPayments { get; set; }
        /// <summary>The archived property</summary>
        public bool? Archived { get; set; }
        /// <summary>The autoApproveInvoice property</summary>
        public bool? AutoApproveInvoice { get; set; }
        /// <summary>The autoCompleteInvoice property</summary>
        public bool? AutoCompleteInvoice { get; set; }
        /// <summary>The backupStorageCountsProducts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_backupStorageCountsProducts>? BackupStorageCountsProducts { get; set; }
#nullable restore
#else
        public List<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_backupStorageCountsProducts> BackupStorageCountsProducts { get; set; }
#endif
        /// <summary>The billBccEmails property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? BillBccEmails { get; set; }
#nullable restore
#else
        public List<string> BillBccEmails { get; set; }
#endif
        /// <summary>The billCcEmails property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? BillCcEmails { get; set; }
#nullable restore
#else
        public List<string> BillCcEmails { get; set; }
#endif
        /// <summary>The billEmails property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? BillEmails { get; set; }
#nullable restore
#else
        public List<string> BillEmails { get; set; }
#endif
        /// <summary>The businessHoursSource property</summary>
        public global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_businessHoursSource? BusinessHoursSource { get; set; }
        /// <summary>Client information associated with this invoice</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_client? Client { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_client Client { get; set; }
#endif
        /// <summary>The contact property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_contact? Contact { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_contact Contact { get; set; }
#endif
        /// <summary>The content property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_content? Content { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_content Content { get; set; }
#endif
        /// <summary>The createTime property</summary>
        public double? CreateTime { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The deviceCountsProducts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_deviceCountsProducts>? DeviceCountsProducts { get; set; }
#nullable restore
#else
        public List<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_deviceCountsProducts> DeviceCountsProducts { get; set; }
#endif
        /// <summary>The displayIncludedTimeOnInvoices property</summary>
        public bool? DisplayIncludedTimeOnInvoices { get; set; }
        /// <summary>The dueDays property</summary>
        public int? DueDays { get; set; }
        /// <summary>The dueDaysSource property</summary>
        public global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_dueDaysSource? DueDaysSource { get; set; }
        /// <summary>The endUserCountsProducts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_endUserCountsProducts>? EndUserCountsProducts { get; set; }
#nullable restore
#else
        public List<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_endUserCountsProducts> EndUserCountsProducts { get; set; }
#endif
        /// <summary>External tax information.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_externalTax? ExternalTax { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_externalTax ExternalTax { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The invoiceGenerationType property</summary>
        public global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_invoiceGenerationType? InvoiceGenerationType { get; set; }
        /// <summary>The invoiceNote property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InvoiceNote { get; set; }
#nullable restore
#else
        public string InvoiceNote { get; set; }
#endif
        /// <summary>The lastBillDate property</summary>
        public double? LastBillDate { get; set; }
        /// <summary>The lastPeriodEndDate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastPeriodEndDate { get; set; }
#nullable restore
#else
        public string LastPeriodEndDate { get; set; }
#endif
        /// <summary>The lastPeriodStartDate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastPeriodStartDate { get; set; }
#nullable restore
#else
        public string LastPeriodStartDate { get; set; }
#endif
        /// <summary>The multiMatchDeviceBackups property</summary>
        public bool? MultiMatchDeviceBackups { get; set; }
        /// <summary>The multiMatchDevices property</summary>
        public bool? MultiMatchDevices { get; set; }
        /// <summary>The multiMatchEndUsers property</summary>
        public bool? MultiMatchEndUsers { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The nextBillDate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NextBillDate { get; set; }
#nullable restore
#else
        public string NextBillDate { get; set; }
#endif
        /// <summary>The nextBillingPeriodStartDate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NextBillingPeriodStartDate { get; set; }
#nullable restore
#else
        public string NextBillingPeriodStartDate { get; set; }
#endif
        /// <summary>The products property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_products>? Products { get; set; }
#nullable restore
#else
        public List<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_products> Products { get; set; }
#endif
        /// <summary>The quickBooks property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_quickBooks? QuickBooks { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_quickBooks QuickBooks { get; set; }
#endif
        /// <summary>The softwareLicenseProducts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_softwareLicenseProducts>? SoftwareLicenseProducts { get; set; }
#nullable restore
#else
        public List<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_softwareLicenseProducts> SoftwareLicenseProducts { get; set; }
#endif
        /// <summary>The taxRate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_taxRate? TaxRate { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_taxRate TaxRate { get; set; }
#endif
        /// <summary>The ticketBillingSettings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_ticketBillingSettings? TicketBillingSettings { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_ticketBillingSettings TicketBillingSettings { get; set; }
#endif
        /// <summary>The timeDefault property</summary>
        public bool? TimeDefault { get; set; }
        /// <summary>The timeEntriesProducts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_timeEntriesProducts>? TimeEntriesProducts { get; set; }
#nullable restore
#else
        public List<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_timeEntriesProducts> TimeEntriesProducts { get; set; }
#endif
        /// <summary>The updateTime property</summary>
        public double? UpdateTime { get; set; }
        /// <summary>The xero property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_xero? Xero { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_xero Xero { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse"/> and sets the default values.
        /// </summary>
        public AgreementsPostResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "active", n => { Active = n.GetBoolValue(); } },
                { "allowOnlineAchPayments", n => { AllowOnlineAchPayments = n.GetBoolValue(); } },
                { "allowOnlineCreditCardPayments", n => { AllowOnlineCreditCardPayments = n.GetBoolValue(); } },
                { "archived", n => { Archived = n.GetBoolValue(); } },
                { "autoApproveInvoice", n => { AutoApproveInvoice = n.GetBoolValue(); } },
                { "autoCompleteInvoice", n => { AutoCompleteInvoice = n.GetBoolValue(); } },
                { "backupStorageCountsProducts", n => { BackupStorageCountsProducts = n.GetCollectionOfObjectValues<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_backupStorageCountsProducts>(global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_backupStorageCountsProducts.CreateFromDiscriminatorValue)?.AsList(); } },
                { "billBccEmails", n => { BillBccEmails = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "billCcEmails", n => { BillCcEmails = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "billEmails", n => { BillEmails = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "businessHoursSource", n => { BusinessHoursSource = n.GetEnumValue<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_businessHoursSource>(); } },
                { "client", n => { Client = n.GetObjectValue<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_client>(global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_client.CreateFromDiscriminatorValue); } },
                { "contact", n => { Contact = n.GetObjectValue<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_contact>(global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_contact.CreateFromDiscriminatorValue); } },
                { "content", n => { Content = n.GetObjectValue<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_content>(global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_content.CreateFromDiscriminatorValue); } },
                { "createTime", n => { CreateTime = n.GetDoubleValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "deviceCountsProducts", n => { DeviceCountsProducts = n.GetCollectionOfObjectValues<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_deviceCountsProducts>(global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_deviceCountsProducts.CreateFromDiscriminatorValue)?.AsList(); } },
                { "displayIncludedTimeOnInvoices", n => { DisplayIncludedTimeOnInvoices = n.GetBoolValue(); } },
                { "dueDays", n => { DueDays = n.GetIntValue(); } },
                { "dueDaysSource", n => { DueDaysSource = n.GetEnumValue<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_dueDaysSource>(); } },
                { "endUserCountsProducts", n => { EndUserCountsProducts = n.GetCollectionOfObjectValues<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_endUserCountsProducts>(global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_endUserCountsProducts.CreateFromDiscriminatorValue)?.AsList(); } },
                { "externalTax", n => { ExternalTax = n.GetObjectValue<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_externalTax>(global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_externalTax.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "invoiceGenerationType", n => { InvoiceGenerationType = n.GetEnumValue<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_invoiceGenerationType>(); } },
                { "invoiceNote", n => { InvoiceNote = n.GetStringValue(); } },
                { "lastBillDate", n => { LastBillDate = n.GetDoubleValue(); } },
                { "lastPeriodEndDate", n => { LastPeriodEndDate = n.GetStringValue(); } },
                { "lastPeriodStartDate", n => { LastPeriodStartDate = n.GetStringValue(); } },
                { "multiMatchDeviceBackups", n => { MultiMatchDeviceBackups = n.GetBoolValue(); } },
                { "multiMatchDevices", n => { MultiMatchDevices = n.GetBoolValue(); } },
                { "multiMatchEndUsers", n => { MultiMatchEndUsers = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "nextBillDate", n => { NextBillDate = n.GetStringValue(); } },
                { "nextBillingPeriodStartDate", n => { NextBillingPeriodStartDate = n.GetStringValue(); } },
                { "products", n => { Products = n.GetCollectionOfObjectValues<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_products>(global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_products.CreateFromDiscriminatorValue)?.AsList(); } },
                { "quickBooks", n => { QuickBooks = n.GetObjectValue<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_quickBooks>(global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_quickBooks.CreateFromDiscriminatorValue); } },
                { "softwareLicenseProducts", n => { SoftwareLicenseProducts = n.GetCollectionOfObjectValues<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_softwareLicenseProducts>(global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_softwareLicenseProducts.CreateFromDiscriminatorValue)?.AsList(); } },
                { "taxRate", n => { TaxRate = n.GetObjectValue<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_taxRate>(global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_taxRate.CreateFromDiscriminatorValue); } },
                { "ticketBillingSettings", n => { TicketBillingSettings = n.GetObjectValue<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_ticketBillingSettings>(global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_ticketBillingSettings.CreateFromDiscriminatorValue); } },
                { "timeDefault", n => { TimeDefault = n.GetBoolValue(); } },
                { "timeEntriesProducts", n => { TimeEntriesProducts = n.GetCollectionOfObjectValues<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_timeEntriesProducts>(global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_timeEntriesProducts.CreateFromDiscriminatorValue)?.AsList(); } },
                { "updateTime", n => { UpdateTime = n.GetDoubleValue(); } },
                { "xero", n => { Xero = n.GetObjectValue<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_xero>(global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_xero.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("active", Active);
            writer.WriteBoolValue("allowOnlineAchPayments", AllowOnlineAchPayments);
            writer.WriteBoolValue("allowOnlineCreditCardPayments", AllowOnlineCreditCardPayments);
            writer.WriteBoolValue("archived", Archived);
            writer.WriteBoolValue("autoApproveInvoice", AutoApproveInvoice);
            writer.WriteBoolValue("autoCompleteInvoice", AutoCompleteInvoice);
            writer.WriteCollectionOfObjectValues<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_backupStorageCountsProducts>("backupStorageCountsProducts", BackupStorageCountsProducts);
            writer.WriteCollectionOfPrimitiveValues<string>("billBccEmails", BillBccEmails);
            writer.WriteCollectionOfPrimitiveValues<string>("billCcEmails", BillCcEmails);
            writer.WriteCollectionOfPrimitiveValues<string>("billEmails", BillEmails);
            writer.WriteEnumValue<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_businessHoursSource>("businessHoursSource", BusinessHoursSource);
            writer.WriteObjectValue<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_client>("client", Client);
            writer.WriteObjectValue<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_contact>("contact", Contact);
            writer.WriteObjectValue<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_content>("content", Content);
            writer.WriteDoubleValue("createTime", CreateTime);
            writer.WriteStringValue("description", Description);
            writer.WriteCollectionOfObjectValues<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_deviceCountsProducts>("deviceCountsProducts", DeviceCountsProducts);
            writer.WriteBoolValue("displayIncludedTimeOnInvoices", DisplayIncludedTimeOnInvoices);
            writer.WriteIntValue("dueDays", DueDays);
            writer.WriteEnumValue<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_dueDaysSource>("dueDaysSource", DueDaysSource);
            writer.WriteCollectionOfObjectValues<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_endUserCountsProducts>("endUserCountsProducts", EndUserCountsProducts);
            writer.WriteObjectValue<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_externalTax>("externalTax", ExternalTax);
            writer.WriteIntValue("id", Id);
            writer.WriteEnumValue<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_invoiceGenerationType>("invoiceGenerationType", InvoiceGenerationType);
            writer.WriteStringValue("invoiceNote", InvoiceNote);
            writer.WriteDoubleValue("lastBillDate", LastBillDate);
            writer.WriteStringValue("lastPeriodEndDate", LastPeriodEndDate);
            writer.WriteStringValue("lastPeriodStartDate", LastPeriodStartDate);
            writer.WriteBoolValue("multiMatchDeviceBackups", MultiMatchDeviceBackups);
            writer.WriteBoolValue("multiMatchDevices", MultiMatchDevices);
            writer.WriteBoolValue("multiMatchEndUsers", MultiMatchEndUsers);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("nextBillDate", NextBillDate);
            writer.WriteStringValue("nextBillingPeriodStartDate", NextBillingPeriodStartDate);
            writer.WriteCollectionOfObjectValues<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_products>("products", Products);
            writer.WriteObjectValue<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_quickBooks>("quickBooks", QuickBooks);
            writer.WriteCollectionOfObjectValues<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_softwareLicenseProducts>("softwareLicenseProducts", SoftwareLicenseProducts);
            writer.WriteObjectValue<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_taxRate>("taxRate", TaxRate);
            writer.WriteObjectValue<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_ticketBillingSettings>("ticketBillingSettings", TicketBillingSettings);
            writer.WriteBoolValue("timeDefault", TimeDefault);
            writer.WriteCollectionOfObjectValues<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_timeEntriesProducts>("timeEntriesProducts", TimeEntriesProducts);
            writer.WriteDoubleValue("updateTime", UpdateTime);
            writer.WriteObjectValue<global::NinjaOne.Client.V2.Billing.Agreements.AgreementsPostResponse_xero>("xero", Xero);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
