// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NinjaOne.Client.V2.Ticketing.Ticket.Item.LogEntry
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum LogEntry_ticketTimeEntry_inHours_billingStatus
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "BILLED")]
        #pragma warning disable CS1591
        BILLED,
        #pragma warning restore CS1591
        [EnumMember(Value = "PENDING")]
        #pragma warning disable CS1591
        PENDING,
        #pragma warning restore CS1591
        [EnumMember(Value = "NOT_BILLABLE")]
        #pragma warning disable CS1591
        NOT_BILLABLE,
        #pragma warning restore CS1591
    }
}
