// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.Attachment;
using NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.Relation;
using NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.Relations;
using NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.Secure;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace NinjaOne.Client.V2.RelatedItems.Entity.Item.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\related-items\entity\{entityType}\{entityId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithEntityItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The attachment property</summary>
        public global::NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.Attachment.AttachmentRequestBuilder Attachment
        {
            get => new global::NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.Attachment.AttachmentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The relation property</summary>
        public global::NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.Relation.RelationRequestBuilder Relation
        {
            get => new global::NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.Relation.RelationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The relations property</summary>
        public global::NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.Relations.RelationsRequestBuilder Relations
        {
            get => new global::NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.Relations.RelationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The secure property</summary>
        public global::NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.Secure.SecureRequestBuilder Secure
        {
            get => new global::NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.Secure.SecureRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.WithEntityItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithEntityItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/related-items/entity/{entityType}/{entityId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.V2.RelatedItems.Entity.Item.Item.WithEntityItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithEntityItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/related-items/entity/{entityType}/{entityId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
