// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NinjaOne.Client.V2.Billing.Products
{
    /// <summary>
    /// Detailed representation of a ninja billing Product response.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProductsPostResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Account ID associated with the product.</summary>
        public int? AccountId { get; set; }
        /// <summary>Indicates if the product is active.</summary>
        public bool? Active { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Additional content/configuration for the product. Structure varies by quantity type.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.Billing.Products.ProductsPostResponse_content? Content { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.Billing.Products.ProductsPostResponse_content Content { get; set; }
#endif
        /// <summary>Timestamp when the product was created.</summary>
        public double? CreateTime { get; set; }
        /// <summary>Description of the product.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Whether the product is a group product.</summary>
        public bool? Group { get; set; }
        /// <summary>Unique identifier of the product.</summary>
        public int? Id { get; set; }
        /// <summary>If 3rd party integration is enabled, the settings for exporting invoices with this product.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.Billing.Products.ProductsPostResponse_integrationSettings? IntegrationSettings { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.Billing.Products.ProductsPostResponse_integrationSettings IntegrationSettings { get; set; }
#endif
        /// <summary>Name of the product.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Representation of a ninja billing product user role response.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.Billing.Products.ProductsPostResponse_productUserRole? ProductUserRole { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.Billing.Products.ProductsPostResponse_productUserRole ProductUserRole { get; set; }
#endif
        /// <summary>Quantity type of the product.</summary>
        public global::NinjaOne.Client.V2.Billing.Products.ProductsPostResponse_quantityType? QuantityType { get; set; }
        /// <summary>Timestamp when the product was last updated.</summary>
        public double? UpdateTime { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.V2.Billing.Products.ProductsPostResponse"/> and sets the default values.
        /// </summary>
        public ProductsPostResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NinjaOne.Client.V2.Billing.Products.ProductsPostResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NinjaOne.Client.V2.Billing.Products.ProductsPostResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::NinjaOne.Client.V2.Billing.Products.ProductsPostResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accountId", n => { AccountId = n.GetIntValue(); } },
                { "active", n => { Active = n.GetBoolValue(); } },
                { "content", n => { Content = n.GetObjectValue<global::NinjaOne.Client.V2.Billing.Products.ProductsPostResponse_content>(global::NinjaOne.Client.V2.Billing.Products.ProductsPostResponse_content.CreateFromDiscriminatorValue); } },
                { "createTime", n => { CreateTime = n.GetDoubleValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "group", n => { Group = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "integrationSettings", n => { IntegrationSettings = n.GetObjectValue<global::NinjaOne.Client.V2.Billing.Products.ProductsPostResponse_integrationSettings>(global::NinjaOne.Client.V2.Billing.Products.ProductsPostResponse_integrationSettings.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "productUserRole", n => { ProductUserRole = n.GetObjectValue<global::NinjaOne.Client.V2.Billing.Products.ProductsPostResponse_productUserRole>(global::NinjaOne.Client.V2.Billing.Products.ProductsPostResponse_productUserRole.CreateFromDiscriminatorValue); } },
                { "quantityType", n => { QuantityType = n.GetEnumValue<global::NinjaOne.Client.V2.Billing.Products.ProductsPostResponse_quantityType>(); } },
                { "updateTime", n => { UpdateTime = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("accountId", AccountId);
            writer.WriteBoolValue("active", Active);
            writer.WriteObjectValue<global::NinjaOne.Client.V2.Billing.Products.ProductsPostResponse_content>("content", Content);
            writer.WriteDoubleValue("createTime", CreateTime);
            writer.WriteStringValue("description", Description);
            writer.WriteBoolValue("group", Group);
            writer.WriteIntValue("id", Id);
            writer.WriteObjectValue<global::NinjaOne.Client.V2.Billing.Products.ProductsPostResponse_integrationSettings>("integrationSettings", IntegrationSettings);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::NinjaOne.Client.V2.Billing.Products.ProductsPostResponse_productUserRole>("productUserRole", ProductUserRole);
            writer.WriteEnumValue<global::NinjaOne.Client.V2.Billing.Products.ProductsPostResponse_quantityType>("quantityType", QuantityType);
            writer.WriteDoubleValue("updateTime", UpdateTime);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
