// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.CustomFields
{
    /// <summary>
    /// Policy condition custom field
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CustomFieldsPostRequestBody_matchAny : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Custom field name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FieldName { get; set; }
#nullable restore
#else
        public string FieldName { get; set; }
#endif
        /// <summary>Custom field operator</summary>
        public global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.CustomFields.CustomFieldsPostRequestBody_matchAny_operator? Operator { get; set; }
        /// <summary>Custom field value</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Value { get; set; }
#nullable restore
#else
        public string Value { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.CustomFields.CustomFieldsPostRequestBody_matchAny"/> and sets the default values.
        /// </summary>
        public CustomFieldsPostRequestBody_matchAny()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.CustomFields.CustomFieldsPostRequestBody_matchAny"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.CustomFields.CustomFieldsPostRequestBody_matchAny CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.CustomFields.CustomFieldsPostRequestBody_matchAny();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "fieldName", n => { FieldName = n.GetStringValue(); } },
                { "operator", n => { Operator = n.GetEnumValue<global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.CustomFields.CustomFieldsPostRequestBody_matchAny_operator>(); } },
                { "value", n => { Value = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("fieldName", FieldName);
            writer.WriteEnumValue<global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.CustomFields.CustomFieldsPostRequestBody_matchAny_operator>("operator", Operator);
            writer.WriteStringValue("value", Value);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
