// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NinjaOne.Client.NinjaRmm.V2.Jobs
{
    /// <summary>Job Type</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Jobs_jobType
    {
        [EnumMember(Value = "ACTIONSET")]
        #pragma warning disable CS1591
        ACTIONSET,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACTION")]
        #pragma warning disable CS1591
        ACTION,
        #pragma warning restore CS1591
        [EnumMember(Value = "CONDITION")]
        #pragma warning disable CS1591
        CONDITION,
        #pragma warning restore CS1591
        [EnumMember(Value = "CONDITION_ACTIONSET")]
        #pragma warning disable CS1591
        CONDITION_ACTIONSET,
        #pragma warning restore CS1591
        [EnumMember(Value = "CONDITION_ACTION")]
        #pragma warning disable CS1591
        CONDITION_ACTION,
        #pragma warning restore CS1591
        [EnumMember(Value = "ANTIVIRUS")]
        #pragma warning disable CS1591
        ANTIVIRUS,
        #pragma warning restore CS1591
        [EnumMember(Value = "PATCH_MANAGEMENT")]
        #pragma warning disable CS1591
        PATCH_MANAGEMENT,
        #pragma warning restore CS1591
        [EnumMember(Value = "TEAMVIEWER")]
        #pragma warning disable CS1591
        TEAMVIEWER,
        #pragma warning restore CS1591
        [EnumMember(Value = "MONITOR")]
        #pragma warning disable CS1591
        MONITOR,
        #pragma warning restore CS1591
        [EnumMember(Value = "SYSTEM")]
        #pragma warning disable CS1591
        SYSTEM,
        #pragma warning restore CS1591
        [EnumMember(Value = "COMMENT")]
        #pragma warning disable CS1591
        COMMENT,
        #pragma warning restore CS1591
        [EnumMember(Value = "SHADOWPROTECT")]
        #pragma warning disable CS1591
        SHADOWPROTECT,
        #pragma warning restore CS1591
        [EnumMember(Value = "IMAGEMANAGER")]
        #pragma warning disable CS1591
        IMAGEMANAGER,
        #pragma warning restore CS1591
        [EnumMember(Value = "HELP_REQUEST")]
        #pragma warning disable CS1591
        HELP_REQUEST,
        #pragma warning restore CS1591
        [EnumMember(Value = "SOFTWARE_PATCH_MANAGEMENT")]
        #pragma warning disable CS1591
        SOFTWARE_PATCH_MANAGEMENT,
        #pragma warning restore CS1591
        [EnumMember(Value = "SPLASHTOP")]
        #pragma warning disable CS1591
        SPLASHTOP,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLOUDBERRY")]
        #pragma warning disable CS1591
        CLOUDBERRY,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLOUDBERRY_BACKUP")]
        #pragma warning disable CS1591
        CLOUDBERRY_BACKUP,
        #pragma warning restore CS1591
        [EnumMember(Value = "SCHEDULED_TASK")]
        #pragma warning disable CS1591
        SCHEDULED_TASK,
        #pragma warning restore CS1591
        [EnumMember(Value = "RDP")]
        #pragma warning disable CS1591
        RDP,
        #pragma warning restore CS1591
        [EnumMember(Value = "SCRIPTING")]
        #pragma warning disable CS1591
        SCRIPTING,
        #pragma warning restore CS1591
        [EnumMember(Value = "SECURITY")]
        #pragma warning disable CS1591
        SECURITY,
        #pragma warning restore CS1591
        [EnumMember(Value = "REMOTE_TOOLS")]
        #pragma warning disable CS1591
        REMOTE_TOOLS,
        #pragma warning restore CS1591
        [EnumMember(Value = "VIRTUALIZATION")]
        #pragma warning disable CS1591
        VIRTUALIZATION,
        #pragma warning restore CS1591
        [EnumMember(Value = "PSA")]
        #pragma warning disable CS1591
        PSA,
        #pragma warning restore CS1591
        [EnumMember(Value = "MDM")]
        #pragma warning disable CS1591
        MDM,
        #pragma warning restore CS1591
        [EnumMember(Value = "NINJA_REMOTE")]
        #pragma warning disable CS1591
        NINJA_REMOTE,
        #pragma warning restore CS1591
        [EnumMember(Value = "NINJA_QUICK_CONNECT")]
        #pragma warning disable CS1591
        NINJA_QUICK_CONNECT,
        #pragma warning restore CS1591
        [EnumMember(Value = "NINJA_NETWORK_DISCOVERY")]
        #pragma warning disable CS1591
        NINJA_NETWORK_DISCOVERY,
        #pragma warning restore CS1591
        [EnumMember(Value = "NINJA_BACKUP")]
        #pragma warning disable CS1591
        NINJA_BACKUP,
        #pragma warning restore CS1591
        [EnumMember(Value = "NINJA_TICKETING")]
        #pragma warning disable CS1591
        NINJA_TICKETING,
        #pragma warning restore CS1591
        [EnumMember(Value = "KNOWLEDGE_BASE")]
        #pragma warning disable CS1591
        KNOWLEDGE_BASE,
        #pragma warning restore CS1591
        [EnumMember(Value = "RELATED_ITEM")]
        #pragma warning disable CS1591
        RELATED_ITEM,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLIENT_CHECKLIST")]
        #pragma warning disable CS1591
        CLIENT_CHECKLIST,
        #pragma warning restore CS1591
        [EnumMember(Value = "CHECKLIST_TEMPLATE")]
        #pragma warning disable CS1591
        CHECKLIST_TEMPLATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "DOCUMENTATION")]
        #pragma warning disable CS1591
        DOCUMENTATION,
        #pragma warning restore CS1591
        [EnumMember(Value = "MICROSOFT_INTUNE")]
        #pragma warning disable CS1591
        MICROSOFT_INTUNE,
        #pragma warning restore CS1591
        [EnumMember(Value = "DYNAMIC_POLICY")]
        #pragma warning disable CS1591
        DYNAMIC_POLICY,
        #pragma warning restore CS1591
    }
}
