// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NinjaOne.Client.V2.Tag.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AssetTypePostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Array of asset IDs to perform bulk operations on (provide the type of asset with the URL)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? AssetIds { get; set; }
#nullable restore
#else
        public List<int?> AssetIds { get; set; }
#endif
        /// <summary>Array of tag IDs to add to the supplied assets</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? TagIdsToAdd { get; set; }
#nullable restore
#else
        public List<int?> TagIdsToAdd { get; set; }
#endif
        /// <summary>Array of tag IDs to remove from the supplied assets</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? TagIdsToRemove { get; set; }
#nullable restore
#else
        public List<int?> TagIdsToRemove { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.V2.Tag.Item.AssetTypePostRequestBody"/> and sets the default values.
        /// </summary>
        public AssetTypePostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NinjaOne.Client.V2.Tag.Item.AssetTypePostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NinjaOne.Client.V2.Tag.Item.AssetTypePostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::NinjaOne.Client.V2.Tag.Item.AssetTypePostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "assetIds", n => { AssetIds = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "tagIdsToAdd", n => { TagIdsToAdd = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "tagIdsToRemove", n => { TagIdsToRemove = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<int?>("assetIds", AssetIds);
            writer.WriteCollectionOfPrimitiveValues<int?>("tagIdsToAdd", TagIdsToAdd);
            writer.WriteCollectionOfPrimitiveValues<int?>("tagIdsToRemove", TagIdsToRemove);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
