// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NinjaOne.Client.V2.Organization.Item.Locations.Backup.Usage
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Usage : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The cloudFileFolderSize property</summary>
        public long? CloudFileFolderSize { get; set; }
        /// <summary>The cloudImageSize property</summary>
        public long? CloudImageSize { get; set; }
        /// <summary>The cloudImageV2Size property</summary>
        public long? CloudImageV2Size { get; set; }
        /// <summary>The cloudNetworkShareSize property</summary>
        public long? CloudNetworkShareSize { get; set; }
        /// <summary>Revisions cloud total size</summary>
        public long? CloudTotalSize { get; private set; }
        /// <summary>The lastFailedBackupJob property</summary>
        public double? LastFailedBackupJob { get; set; }
        /// <summary>The lastSuccessfulBackupJob property</summary>
        public double? LastSuccessfulBackupJob { get; set; }
        /// <summary>The localFileFolderSize property</summary>
        public long? LocalFileFolderSize { get; set; }
        /// <summary>The localImageSize property</summary>
        public long? LocalImageSize { get; set; }
        /// <summary>The localImageV2Size property</summary>
        public long? LocalImageV2Size { get; set; }
        /// <summary>Revisions local total size</summary>
        public long? LocalTotalSize { get; private set; }
        /// <summary>Device location description</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LocationDescription { get; set; }
#nullable restore
#else
        public string LocationDescription { get; set; }
#endif
        /// <summary>Device location id</summary>
        public int? LocationId { get; set; }
        /// <summary>Device location name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LocationName { get; set; }
#nullable restore
#else
        public string LocationName { get; set; }
#endif
        /// <summary>The organizationId property</summary>
        public int? OrganizationId { get; set; }
        /// <summary>The organizationName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationName { get; set; }
#nullable restore
#else
        public string OrganizationName { get; set; }
#endif
        /// <summary>The revisionsCurrentSize property</summary>
        public long? RevisionsCurrentSize { get; set; }
        /// <summary>The revisionsDeletedSize property</summary>
        public long? RevisionsDeletedSize { get; set; }
        /// <summary>The revisionsPreviousSize property</summary>
        public long? RevisionsPreviousSize { get; set; }
        /// <summary>Revisions total size</summary>
        public long? RevisionsTotalSize { get; private set; }
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.V2.Organization.Item.Locations.Backup.Usage.Usage"/> and sets the default values.
        /// </summary>
        public Usage()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NinjaOne.Client.V2.Organization.Item.Locations.Backup.Usage.Usage"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NinjaOne.Client.V2.Organization.Item.Locations.Backup.Usage.Usage CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::NinjaOne.Client.V2.Organization.Item.Locations.Backup.Usage.Usage();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cloudFileFolderSize", n => { CloudFileFolderSize = n.GetLongValue(); } },
                { "cloudImageSize", n => { CloudImageSize = n.GetLongValue(); } },
                { "cloudImageV2Size", n => { CloudImageV2Size = n.GetLongValue(); } },
                { "cloudNetworkShareSize", n => { CloudNetworkShareSize = n.GetLongValue(); } },
                { "cloudTotalSize", n => { CloudTotalSize = n.GetLongValue(); } },
                { "lastFailedBackupJob", n => { LastFailedBackupJob = n.GetDoubleValue(); } },
                { "lastSuccessfulBackupJob", n => { LastSuccessfulBackupJob = n.GetDoubleValue(); } },
                { "localFileFolderSize", n => { LocalFileFolderSize = n.GetLongValue(); } },
                { "localImageSize", n => { LocalImageSize = n.GetLongValue(); } },
                { "localImageV2Size", n => { LocalImageV2Size = n.GetLongValue(); } },
                { "localTotalSize", n => { LocalTotalSize = n.GetLongValue(); } },
                { "locationDescription", n => { LocationDescription = n.GetStringValue(); } },
                { "locationId", n => { LocationId = n.GetIntValue(); } },
                { "locationName", n => { LocationName = n.GetStringValue(); } },
                { "organizationId", n => { OrganizationId = n.GetIntValue(); } },
                { "organizationName", n => { OrganizationName = n.GetStringValue(); } },
                { "revisionsCurrentSize", n => { RevisionsCurrentSize = n.GetLongValue(); } },
                { "revisionsDeletedSize", n => { RevisionsDeletedSize = n.GetLongValue(); } },
                { "revisionsPreviousSize", n => { RevisionsPreviousSize = n.GetLongValue(); } },
                { "revisionsTotalSize", n => { RevisionsTotalSize = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("cloudFileFolderSize", CloudFileFolderSize);
            writer.WriteLongValue("cloudImageSize", CloudImageSize);
            writer.WriteLongValue("cloudImageV2Size", CloudImageV2Size);
            writer.WriteLongValue("cloudNetworkShareSize", CloudNetworkShareSize);
            writer.WriteDoubleValue("lastFailedBackupJob", LastFailedBackupJob);
            writer.WriteDoubleValue("lastSuccessfulBackupJob", LastSuccessfulBackupJob);
            writer.WriteLongValue("localFileFolderSize", LocalFileFolderSize);
            writer.WriteLongValue("localImageSize", LocalImageSize);
            writer.WriteLongValue("localImageV2Size", LocalImageV2Size);
            writer.WriteStringValue("locationDescription", LocationDescription);
            writer.WriteIntValue("locationId", LocationId);
            writer.WriteStringValue("locationName", LocationName);
            writer.WriteIntValue("organizationId", OrganizationId);
            writer.WriteStringValue("organizationName", OrganizationName);
            writer.WriteLongValue("revisionsCurrentSize", RevisionsCurrentSize);
            writer.WriteLongValue("revisionsDeletedSize", RevisionsDeletedSize);
            writer.WriteLongValue("revisionsPreviousSize", RevisionsPreviousSize);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
