// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using NinjaOne.Client.V2.DocumentTemplates.Item.Archive;
using NinjaOne.Client.V2.DocumentTemplates.Item.Restore;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace NinjaOne.Client.V2.DocumentTemplates.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\document-templates\{documentTemplateId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithDocumentTemplateItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The archive property</summary>
        public global::NinjaOne.Client.V2.DocumentTemplates.Item.Archive.ArchiveRequestBuilder Archive
        {
            get => new global::NinjaOne.Client.V2.DocumentTemplates.Item.Archive.ArchiveRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The restore property</summary>
        public global::NinjaOne.Client.V2.DocumentTemplates.Item.Restore.RestoreRequestBuilder Restore
        {
            get => new global::NinjaOne.Client.V2.DocumentTemplates.Item.Restore.RestoreRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.V2.DocumentTemplates.Item.WithDocumentTemplateItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDocumentTemplateItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/document-templates/{documentTemplateId}{?includeTechnicianRoles*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.V2.DocumentTemplates.Item.WithDocumentTemplateItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDocumentTemplateItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/document-templates/{documentTemplateId}{?includeTechnicianRoles*}", rawUrl)
        {
        }
        /// <summary>
        /// Deletes a document template by id
        /// </summary>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            await RequestAdapter.SendNoContentAsync(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get document template
        /// </summary>
        /// <returns>A <see cref="global::NinjaOne.Client.V2.DocumentTemplates.Item.WithDocumentTemplateGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::NinjaOne.Client.V2.DocumentTemplates.Item.WithDocumentTemplateGetResponse?> GetAsWithDocumentTemplateGetResponseAsync(Action<RequestConfiguration<global::NinjaOne.Client.V2.DocumentTemplates.Item.WithDocumentTemplateItemRequestBuilder.WithDocumentTemplateItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::NinjaOne.Client.V2.DocumentTemplates.Item.WithDocumentTemplateGetResponse> GetAsWithDocumentTemplateGetResponseAsync(Action<RequestConfiguration<global::NinjaOne.Client.V2.DocumentTemplates.Item.WithDocumentTemplateItemRequestBuilder.WithDocumentTemplateItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::NinjaOne.Client.V2.DocumentTemplates.Item.WithDocumentTemplateGetResponse>(requestInfo, global::NinjaOne.Client.V2.DocumentTemplates.Item.WithDocumentTemplateGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get document template
        /// </summary>
        /// <returns>A <see cref="global::NinjaOne.Client.V2.DocumentTemplates.Item.WithDocumentTemplateResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use GetAsWithDocumentTemplateGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::NinjaOne.Client.V2.DocumentTemplates.Item.WithDocumentTemplateResponse?> GetAsync(Action<RequestConfiguration<global::NinjaOne.Client.V2.DocumentTemplates.Item.WithDocumentTemplateItemRequestBuilder.WithDocumentTemplateItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::NinjaOne.Client.V2.DocumentTemplates.Item.WithDocumentTemplateResponse> GetAsync(Action<RequestConfiguration<global::NinjaOne.Client.V2.DocumentTemplates.Item.WithDocumentTemplateItemRequestBuilder.WithDocumentTemplateItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::NinjaOne.Client.V2.DocumentTemplates.Item.WithDocumentTemplateResponse>(requestInfo, global::NinjaOne.Client.V2.DocumentTemplates.Item.WithDocumentTemplateResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Updates a document template by id
        /// </summary>
        /// <returns>A <see cref="global::NinjaOne.Client.V2.DocumentTemplates.Item.WithDocumentTemplatePutResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::NinjaOne.Client.V2.DocumentTemplates.Item.WithDocumentTemplatePutResponse?> PutAsWithDocumentTemplatePutResponseAsync(global::NinjaOne.Client.V2.DocumentTemplates.Item.WithDocumentTemplatePutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::NinjaOne.Client.V2.DocumentTemplates.Item.WithDocumentTemplatePutResponse> PutAsWithDocumentTemplatePutResponseAsync(global::NinjaOne.Client.V2.DocumentTemplates.Item.WithDocumentTemplatePutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::NinjaOne.Client.V2.DocumentTemplates.Item.WithDocumentTemplatePutResponse>(requestInfo, global::NinjaOne.Client.V2.DocumentTemplates.Item.WithDocumentTemplatePutResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Updates a document template by id
        /// </summary>
        /// <returns>A <see cref="global::NinjaOne.Client.V2.DocumentTemplates.Item.WithDocumentTemplateResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use PutAsWithDocumentTemplatePutResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::NinjaOne.Client.V2.DocumentTemplates.Item.WithDocumentTemplateResponse?> PutAsync(global::NinjaOne.Client.V2.DocumentTemplates.Item.WithDocumentTemplatePutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::NinjaOne.Client.V2.DocumentTemplates.Item.WithDocumentTemplateResponse> PutAsync(global::NinjaOne.Client.V2.DocumentTemplates.Item.WithDocumentTemplatePutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::NinjaOne.Client.V2.DocumentTemplates.Item.WithDocumentTemplateResponse>(requestInfo, global::NinjaOne.Client.V2.DocumentTemplates.Item.WithDocumentTemplateResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Deletes a document template by id
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            return requestInfo;
        }
        /// <summary>
        /// Get document template
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::NinjaOne.Client.V2.DocumentTemplates.Item.WithDocumentTemplateItemRequestBuilder.WithDocumentTemplateItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::NinjaOne.Client.V2.DocumentTemplates.Item.WithDocumentTemplateItemRequestBuilder.WithDocumentTemplateItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Updates a document template by id
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::NinjaOne.Client.V2.DocumentTemplates.Item.WithDocumentTemplatePutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::NinjaOne.Client.V2.DocumentTemplates.Item.WithDocumentTemplatePutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::NinjaOne.Client.V2.DocumentTemplates.Item.WithDocumentTemplateItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::NinjaOne.Client.V2.DocumentTemplates.Item.WithDocumentTemplateItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::NinjaOne.Client.V2.DocumentTemplates.Item.WithDocumentTemplateItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithDocumentTemplateItemRequestBuilderDeleteRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Get document template
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithDocumentTemplateItemRequestBuilderGetQueryParameters 
        {
            /// <summary>Includes allowed technician roles.</summary>
            [QueryParameter("includeTechnicianRoles")]
            public bool? IncludeTechnicianRoles { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithDocumentTemplateItemRequestBuilderGetRequestConfiguration : RequestConfiguration<global::NinjaOne.Client.V2.DocumentTemplates.Item.WithDocumentTemplateItemRequestBuilder.WithDocumentTemplateItemRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithDocumentTemplateItemRequestBuilderPutRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
