// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NinjaOne.Client.V2.Devices.Search
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Search5XXError_devices_references_assignedOwner_invitationStatus
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "REGISTERED")]
        #pragma warning disable CS1591
        REGISTERED,
        #pragma warning restore CS1591
        [EnumMember(Value = "PENDING")]
        #pragma warning disable CS1591
        PENDING,
        #pragma warning restore CS1591
        [EnumMember(Value = "EXPIRED")]
        #pragma warning disable CS1591
        EXPIRED,
        #pragma warning restore CS1591
    }
}
