// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NinjaOne.Client.V2.Device.Item
{
    /// <summary>
    /// Expanded entity references
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DeviceGetResponse_references : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Assigned device owner</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_assignedOwner? AssignedOwner { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_assignedOwner AssignedOwner { get; set; }
#endif
        /// <summary>Device Backup Bandwidth Throttle</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_backupBandwidthThrottle? BackupBandwidthThrottle { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_backupBandwidthThrottle BackupBandwidthThrottle { get; set; }
#endif
        /// <summary>Device Backup Usage</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_backupUsage? BackupUsage { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_backupUsage BackupUsage { get; set; }
#endif
        /// <summary>Location</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_location? Location { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_location Location { get; set; }
#endif
        /// <summary>Organization</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_organization? Organization { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_organization Organization { get; set; }
#endif
        /// <summary>Assigned policy (overrides organization and location policy mapping)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_policy? Policy { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_policy Policy { get; set; }
#endif
        /// <summary>Device Role</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_role? Role { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_role Role { get; set; }
#endif
        /// <summary>Assigned policy (overrides organization and location policy mapping)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_rolePolicy? RolePolicy { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_rolePolicy RolePolicy { get; set; }
#endif
        /// <summary>Warranty Info</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_warranty? Warranty { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_warranty Warranty { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references"/> and sets the default values.
        /// </summary>
        public DeviceGetResponse_references()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "assignedOwner", n => { AssignedOwner = n.GetObjectValue<global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_assignedOwner>(global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_assignedOwner.CreateFromDiscriminatorValue); } },
                { "backupBandwidthThrottle", n => { BackupBandwidthThrottle = n.GetObjectValue<global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_backupBandwidthThrottle>(global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_backupBandwidthThrottle.CreateFromDiscriminatorValue); } },
                { "backupUsage", n => { BackupUsage = n.GetObjectValue<global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_backupUsage>(global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_backupUsage.CreateFromDiscriminatorValue); } },
                { "location", n => { Location = n.GetObjectValue<global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_location>(global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_location.CreateFromDiscriminatorValue); } },
                { "organization", n => { Organization = n.GetObjectValue<global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_organization>(global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_organization.CreateFromDiscriminatorValue); } },
                { "policy", n => { Policy = n.GetObjectValue<global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_policy>(global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_policy.CreateFromDiscriminatorValue); } },
                { "role", n => { Role = n.GetObjectValue<global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_role>(global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_role.CreateFromDiscriminatorValue); } },
                { "rolePolicy", n => { RolePolicy = n.GetObjectValue<global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_rolePolicy>(global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_rolePolicy.CreateFromDiscriminatorValue); } },
                { "warranty", n => { Warranty = n.GetObjectValue<global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_warranty>(global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_warranty.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_assignedOwner>("assignedOwner", AssignedOwner);
            writer.WriteObjectValue<global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_backupBandwidthThrottle>("backupBandwidthThrottle", BackupBandwidthThrottle);
            writer.WriteObjectValue<global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_backupUsage>("backupUsage", BackupUsage);
            writer.WriteObjectValue<global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_location>("location", Location);
            writer.WriteObjectValue<global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_organization>("organization", Organization);
            writer.WriteObjectValue<global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_policy>("policy", Policy);
            writer.WriteObjectValue<global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_role>("role", Role);
            writer.WriteObjectValue<global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_rolePolicy>("rolePolicy", RolePolicy);
            writer.WriteObjectValue<global::NinjaOne.Client.V2.Device.Item.DeviceGetResponse_references_warranty>("warranty", Warranty);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
