// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NinjaOne.Client.V2.Ticketing.TicketForm.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum TicketForm5XXError_fields_content_advancedSettings_identifier_assignTo
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "NEW_ASSETS_ONLY")]
        #pragma warning disable CS1591
        NEW_ASSETS_ONLY,
        #pragma warning restore CS1591
        [EnumMember(Value = "NEW_AND_EXISTING_ASSETS")]
        #pragma warning disable CS1591
        NEW_AND_EXISTING_ASSETS,
        #pragma warning restore CS1591
    }
}
