// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NinjaOne.Client.V2.Tab
{
    /// <summary>Type of technician permission on the attribute</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TabPostResponse_items_technicianPermission
    {
        [EnumMember(Value = "NONE")]
        #pragma warning disable CS1591
        NONE,
        #pragma warning restore CS1591
        [EnumMember(Value = "EDITABLE")]
        #pragma warning disable CS1591
        EDITABLE,
        #pragma warning restore CS1591
        [EnumMember(Value = "READ_ONLY")]
        #pragma warning disable CS1591
        READ_ONLY,
        #pragma warning restore CS1591
    }
}
