// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NinjaOne.Client.V2.Tab
{
    /// <summary>Definition scopes of the attribute</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TabPostResponse_items_definitionScope
    {
        [EnumMember(Value = "NODE")]
        #pragma warning disable CS1591
        NODE,
        #pragma warning restore CS1591
        [EnumMember(Value = "END_USER")]
        #pragma warning disable CS1591
        END_USER,
        #pragma warning restore CS1591
        [EnumMember(Value = "LOCATION")]
        #pragma warning disable CS1591
        LOCATION,
        #pragma warning restore CS1591
        [EnumMember(Value = "ORGANIZATION")]
        #pragma warning disable CS1591
        ORGANIZATION,
        #pragma warning restore CS1591
    }
}
