// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NinjaOne.Client.V2.Organization.Restore
{
    /// <summary>
    /// Checklist&apos;s tasks
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Restore_tasks : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Archive by user</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.Organization.Restore.Restore_tasks_assignedTo? AssignedTo { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.Organization.Restore.Restore_tasks_assignedTo AssignedTo { get; set; }
#endif
        /// <summary>Indicates if the checklist is completed</summary>
        public bool? Completed { get; set; }
        /// <summary>Archive by user</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.Organization.Restore.Restore_tasks_completedBy? CompletedBy { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.Organization.Restore.Restore_tasks_completedBy CompletedBy { get; set; }
#endif
        /// <summary>Date of completion</summary>
        public double? CompletedOn { get; set; }
        /// <summary>Task description</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.Organization.Restore.Restore_tasks_description? Description { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.Organization.Restore.Restore_tasks_description Description { get; set; }
#endif
        /// <summary>Due date</summary>
        public double? DueDate { get; set; }
        /// <summary>Identifier</summary>
        public int? Id { get; set; }
        /// <summary>Task name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Position of the task</summary>
        public int? Position { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.V2.Organization.Restore.Restore_tasks"/> and sets the default values.
        /// </summary>
        public Restore_tasks()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NinjaOne.Client.V2.Organization.Restore.Restore_tasks"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NinjaOne.Client.V2.Organization.Restore.Restore_tasks CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::NinjaOne.Client.V2.Organization.Restore.Restore_tasks();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "assignedTo", n => { AssignedTo = n.GetObjectValue<global::NinjaOne.Client.V2.Organization.Restore.Restore_tasks_assignedTo>(global::NinjaOne.Client.V2.Organization.Restore.Restore_tasks_assignedTo.CreateFromDiscriminatorValue); } },
                { "completed", n => { Completed = n.GetBoolValue(); } },
                { "completedBy", n => { CompletedBy = n.GetObjectValue<global::NinjaOne.Client.V2.Organization.Restore.Restore_tasks_completedBy>(global::NinjaOne.Client.V2.Organization.Restore.Restore_tasks_completedBy.CreateFromDiscriminatorValue); } },
                { "completedOn", n => { CompletedOn = n.GetDoubleValue(); } },
                { "description", n => { Description = n.GetObjectValue<global::NinjaOne.Client.V2.Organization.Restore.Restore_tasks_description>(global::NinjaOne.Client.V2.Organization.Restore.Restore_tasks_description.CreateFromDiscriminatorValue); } },
                { "dueDate", n => { DueDate = n.GetDoubleValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "position", n => { Position = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::NinjaOne.Client.V2.Organization.Restore.Restore_tasks_assignedTo>("assignedTo", AssignedTo);
            writer.WriteBoolValue("completed", Completed);
            writer.WriteObjectValue<global::NinjaOne.Client.V2.Organization.Restore.Restore_tasks_completedBy>("completedBy", CompletedBy);
            writer.WriteDoubleValue("completedOn", CompletedOn);
            writer.WriteObjectValue<global::NinjaOne.Client.V2.Organization.Restore.Restore_tasks_description>("description", Description);
            writer.WriteDoubleValue("dueDate", DueDate);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("position", Position);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
