// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using NinjaOne.Client.V2.Contact.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace NinjaOne.Client.V2.Contact
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\contact
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ContactRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the NinjaOne.Client.v2.contact.item collection</summary>
        /// <param name="position">Contact identifier</param>
        /// <returns>A <see cref="global::NinjaOne.Client.V2.Contact.Item.ContactItemRequestBuilder"/></returns>
        public global::NinjaOne.Client.V2.Contact.Item.ContactItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::NinjaOne.Client.V2.Contact.Item.ContactItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the NinjaOne.Client.v2.contact.item collection</summary>
        /// <param name="position">Contact identifier</param>
        /// <returns>A <see cref="global::NinjaOne.Client.V2.Contact.Item.ContactItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::NinjaOne.Client.V2.Contact.Item.ContactItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("id", position);
                return new global::NinjaOne.Client.V2.Contact.Item.ContactItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.V2.Contact.ContactRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ContactRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/contact", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.V2.Contact.ContactRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ContactRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/contact", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
