// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using NinjaOne.Client.NinjaRmm.Models;
using System.Collections.Generic;
using System.IO;
using System;
namespace NinjaOne.Client.NinjaRmm.V2.Attachments.Temp.Upload
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UploadPostRequestBody_files_parent : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The bodyParts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::NinjaOne.Client.NinjaRmm.Models.BodyPart>? BodyParts { get; set; }
#nullable restore
#else
        public List<global::NinjaOne.Client.NinjaRmm.Models.BodyPart> BodyParts { get; set; }
#endif
        /// <summary>The contentDisposition property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.NinjaRmm.V2.Attachments.Temp.Upload.UploadPostRequestBody_files_parent_contentDisposition? ContentDisposition { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.NinjaRmm.V2.Attachments.Temp.Upload.UploadPostRequestBody_files_parent_contentDisposition ContentDisposition { get; set; }
#endif
        /// <summary>The entity property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.NinjaRmm.V2.Attachments.Temp.Upload.UploadPostRequestBody_files_parent_entity? Entity { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.NinjaRmm.V2.Attachments.Temp.Upload.UploadPostRequestBody_files_parent_entity Entity { get; set; }
#endif
        /// <summary>The headers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.NinjaRmm.V2.Attachments.Temp.Upload.UploadPostRequestBody_files_parent_headers? Headers { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.NinjaRmm.V2.Attachments.Temp.Upload.UploadPostRequestBody_files_parent_headers Headers { get; set; }
#endif
        /// <summary>The mediaType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.NinjaRmm.V2.Attachments.Temp.Upload.UploadPostRequestBody_files_parent_mediaType? MediaType { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.NinjaRmm.V2.Attachments.Temp.Upload.UploadPostRequestBody_files_parent_mediaType MediaType { get; set; }
#endif
        /// <summary>The messageBodyWorkers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.NinjaRmm.V2.Attachments.Temp.Upload.UploadPostRequestBody_files_parent_messageBodyWorkers? MessageBodyWorkers { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.NinjaRmm.V2.Attachments.Temp.Upload.UploadPostRequestBody_files_parent_messageBodyWorkers MessageBodyWorkers { get; set; }
#endif
        /// <summary>The parameterizedHeaders property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.NinjaRmm.V2.Attachments.Temp.Upload.UploadPostRequestBody_files_parent_parameterizedHeaders? ParameterizedHeaders { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.NinjaRmm.V2.Attachments.Temp.Upload.UploadPostRequestBody_files_parent_parameterizedHeaders ParameterizedHeaders { get; set; }
#endif
        /// <summary>The parent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.NinjaRmm.Models.MultiPart? Parent { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.NinjaRmm.Models.MultiPart Parent { get; set; }
#endif
        /// <summary>The providers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.NinjaRmm.V2.Attachments.Temp.Upload.UploadPostRequestBody_files_parent_providers? Providers { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.NinjaRmm.V2.Attachments.Temp.Upload.UploadPostRequestBody_files_parent_providers Providers { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.NinjaRmm.V2.Attachments.Temp.Upload.UploadPostRequestBody_files_parent"/> and sets the default values.
        /// </summary>
        public UploadPostRequestBody_files_parent()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NinjaOne.Client.NinjaRmm.V2.Attachments.Temp.Upload.UploadPostRequestBody_files_parent"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NinjaOne.Client.NinjaRmm.V2.Attachments.Temp.Upload.UploadPostRequestBody_files_parent CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::NinjaOne.Client.NinjaRmm.V2.Attachments.Temp.Upload.UploadPostRequestBody_files_parent();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bodyParts", n => { BodyParts = n.GetCollectionOfObjectValues<global::NinjaOne.Client.NinjaRmm.Models.BodyPart>(global::NinjaOne.Client.NinjaRmm.Models.BodyPart.CreateFromDiscriminatorValue)?.AsList(); } },
                { "contentDisposition", n => { ContentDisposition = n.GetObjectValue<global::NinjaOne.Client.NinjaRmm.V2.Attachments.Temp.Upload.UploadPostRequestBody_files_parent_contentDisposition>(global::NinjaOne.Client.NinjaRmm.V2.Attachments.Temp.Upload.UploadPostRequestBody_files_parent_contentDisposition.CreateFromDiscriminatorValue); } },
                { "entity", n => { Entity = n.GetObjectValue<global::NinjaOne.Client.NinjaRmm.V2.Attachments.Temp.Upload.UploadPostRequestBody_files_parent_entity>(global::NinjaOne.Client.NinjaRmm.V2.Attachments.Temp.Upload.UploadPostRequestBody_files_parent_entity.CreateFromDiscriminatorValue); } },
                { "headers", n => { Headers = n.GetObjectValue<global::NinjaOne.Client.NinjaRmm.V2.Attachments.Temp.Upload.UploadPostRequestBody_files_parent_headers>(global::NinjaOne.Client.NinjaRmm.V2.Attachments.Temp.Upload.UploadPostRequestBody_files_parent_headers.CreateFromDiscriminatorValue); } },
                { "mediaType", n => { MediaType = n.GetObjectValue<global::NinjaOne.Client.NinjaRmm.V2.Attachments.Temp.Upload.UploadPostRequestBody_files_parent_mediaType>(global::NinjaOne.Client.NinjaRmm.V2.Attachments.Temp.Upload.UploadPostRequestBody_files_parent_mediaType.CreateFromDiscriminatorValue); } },
                { "messageBodyWorkers", n => { MessageBodyWorkers = n.GetObjectValue<global::NinjaOne.Client.NinjaRmm.V2.Attachments.Temp.Upload.UploadPostRequestBody_files_parent_messageBodyWorkers>(global::NinjaOne.Client.NinjaRmm.V2.Attachments.Temp.Upload.UploadPostRequestBody_files_parent_messageBodyWorkers.CreateFromDiscriminatorValue); } },
                { "parameterizedHeaders", n => { ParameterizedHeaders = n.GetObjectValue<global::NinjaOne.Client.NinjaRmm.V2.Attachments.Temp.Upload.UploadPostRequestBody_files_parent_parameterizedHeaders>(global::NinjaOne.Client.NinjaRmm.V2.Attachments.Temp.Upload.UploadPostRequestBody_files_parent_parameterizedHeaders.CreateFromDiscriminatorValue); } },
                { "parent", n => { Parent = n.GetObjectValue<global::NinjaOne.Client.NinjaRmm.Models.MultiPart>(global::NinjaOne.Client.NinjaRmm.Models.MultiPart.CreateFromDiscriminatorValue); } },
                { "providers", n => { Providers = n.GetObjectValue<global::NinjaOne.Client.NinjaRmm.V2.Attachments.Temp.Upload.UploadPostRequestBody_files_parent_providers>(global::NinjaOne.Client.NinjaRmm.V2.Attachments.Temp.Upload.UploadPostRequestBody_files_parent_providers.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::NinjaOne.Client.NinjaRmm.Models.BodyPart>("bodyParts", BodyParts);
            writer.WriteObjectValue<global::NinjaOne.Client.NinjaRmm.V2.Attachments.Temp.Upload.UploadPostRequestBody_files_parent_contentDisposition>("contentDisposition", ContentDisposition);
            writer.WriteObjectValue<global::NinjaOne.Client.NinjaRmm.V2.Attachments.Temp.Upload.UploadPostRequestBody_files_parent_entity>("entity", Entity);
            writer.WriteObjectValue<global::NinjaOne.Client.NinjaRmm.V2.Attachments.Temp.Upload.UploadPostRequestBody_files_parent_headers>("headers", Headers);
            writer.WriteObjectValue<global::NinjaOne.Client.NinjaRmm.V2.Attachments.Temp.Upload.UploadPostRequestBody_files_parent_mediaType>("mediaType", MediaType);
            writer.WriteObjectValue<global::NinjaOne.Client.NinjaRmm.V2.Attachments.Temp.Upload.UploadPostRequestBody_files_parent_messageBodyWorkers>("messageBodyWorkers", MessageBodyWorkers);
            writer.WriteObjectValue<global::NinjaOne.Client.NinjaRmm.V2.Attachments.Temp.Upload.UploadPostRequestBody_files_parent_parameterizedHeaders>("parameterizedHeaders", ParameterizedHeaders);
            writer.WriteObjectValue<global::NinjaOne.Client.NinjaRmm.Models.MultiPart>("parent", Parent);
            writer.WriteObjectValue<global::NinjaOne.Client.NinjaRmm.V2.Attachments.Temp.Upload.UploadPostRequestBody_files_parent_providers>("providers", Providers);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
