// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NinjaOne.Client.V2.Billing.Invoices
{
    /// <summary>
    /// Representation of an invoice product/line item.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InvoicesPostResponse_agreementProducts : IAdditionalDataHolder, IParsable
    {
        /// <summary>Account ID.</summary>
        public int? AccountId { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Agreement product ID.</summary>
        public int? AgreementProductId { get; set; }
        /// <summary>Billing period end date.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BillingPeriodEndDate { get; set; }
#nullable restore
#else
        public string BillingPeriodEndDate { get; set; }
#endif
        /// <summary>Billing period start date.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BillingPeriodStartDate { get; set; }
#nullable restore
#else
        public string BillingPeriodStartDate { get; set; }
#endif
        /// <summary>Cost.</summary>
        public double? Cost { get; set; }
        /// <summary>Created date.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreateTime { get; set; }
#nullable restore
#else
        public string CreateTime { get; set; }
#endif
        /// <summary>Description.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Discount amount.</summary>
        public double? Discount { get; set; }
        /// <summary>Whether this is a product group.</summary>
        public bool? Group { get; set; }
        /// <summary>Unique identifier of the invoice product.</summary>
        public int? Id { get; set; }
        /// <summary>Integration settings for invoice product.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.Billing.Invoices.InvoicesPostResponse_agreementProducts_integrationSettings? IntegrationSettings { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.Billing.Invoices.InvoicesPostResponse_agreementProducts_integrationSettings IntegrationSettings { get; set; }
#endif
        /// <summary>Product name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Unit price.</summary>
        public double? Price { get; set; }
        /// <summary>Product ID from catalog.</summary>
        public int? ProductId { get; set; }
        /// <summary>Product IDs if this is a group.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? ProductIds { get; set; }
#nullable restore
#else
        public List<int?> ProductIds { get; set; }
#endif
        /// <summary>Quantity.</summary>
        public double? Quantity { get; set; }
        /// <summary>Quantity type.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? QuantityType { get; set; }
#nullable restore
#else
        public string QuantityType { get; set; }
#endif
        /// <summary>Subtotal before discount.</summary>
        public double? SubTotal { get; set; }
        /// <summary>Subtotal after discount.</summary>
        public double? SubTotalWithDiscount { get; set; }
        /// <summary>Whether the product is taxable.</summary>
        public bool? Taxable { get; set; }
        /// <summary>Tax rate applied.</summary>
        public double? TaxRate { get; set; }
        /// <summary>Ticket product ID.</summary>
        public int? TicketProductId { get; set; }
        /// <summary>Total amount including tax.</summary>
        public double? Total { get; set; }
        /// <summary>Total tax amount.</summary>
        public double? TotalTax { get; set; }
        /// <summary>Last update date.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdateTime { get; set; }
#nullable restore
#else
        public string UpdateTime { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.V2.Billing.Invoices.InvoicesPostResponse_agreementProducts"/> and sets the default values.
        /// </summary>
        public InvoicesPostResponse_agreementProducts()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NinjaOne.Client.V2.Billing.Invoices.InvoicesPostResponse_agreementProducts"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NinjaOne.Client.V2.Billing.Invoices.InvoicesPostResponse_agreementProducts CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::NinjaOne.Client.V2.Billing.Invoices.InvoicesPostResponse_agreementProducts();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accountId", n => { AccountId = n.GetIntValue(); } },
                { "agreementProductId", n => { AgreementProductId = n.GetIntValue(); } },
                { "billingPeriodEndDate", n => { BillingPeriodEndDate = n.GetStringValue(); } },
                { "billingPeriodStartDate", n => { BillingPeriodStartDate = n.GetStringValue(); } },
                { "cost", n => { Cost = n.GetDoubleValue(); } },
                { "createTime", n => { CreateTime = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "discount", n => { Discount = n.GetDoubleValue(); } },
                { "group", n => { Group = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "integrationSettings", n => { IntegrationSettings = n.GetObjectValue<global::NinjaOne.Client.V2.Billing.Invoices.InvoicesPostResponse_agreementProducts_integrationSettings>(global::NinjaOne.Client.V2.Billing.Invoices.InvoicesPostResponse_agreementProducts_integrationSettings.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "price", n => { Price = n.GetDoubleValue(); } },
                { "productId", n => { ProductId = n.GetIntValue(); } },
                { "productIds", n => { ProductIds = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "quantity", n => { Quantity = n.GetDoubleValue(); } },
                { "quantityType", n => { QuantityType = n.GetStringValue(); } },
                { "subTotal", n => { SubTotal = n.GetDoubleValue(); } },
                { "subTotalWithDiscount", n => { SubTotalWithDiscount = n.GetDoubleValue(); } },
                { "taxRate", n => { TaxRate = n.GetDoubleValue(); } },
                { "taxable", n => { Taxable = n.GetBoolValue(); } },
                { "ticketProductId", n => { TicketProductId = n.GetIntValue(); } },
                { "total", n => { Total = n.GetDoubleValue(); } },
                { "totalTax", n => { TotalTax = n.GetDoubleValue(); } },
                { "updateTime", n => { UpdateTime = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("accountId", AccountId);
            writer.WriteIntValue("agreementProductId", AgreementProductId);
            writer.WriteStringValue("billingPeriodEndDate", BillingPeriodEndDate);
            writer.WriteStringValue("billingPeriodStartDate", BillingPeriodStartDate);
            writer.WriteDoubleValue("cost", Cost);
            writer.WriteStringValue("createTime", CreateTime);
            writer.WriteStringValue("description", Description);
            writer.WriteDoubleValue("discount", Discount);
            writer.WriteBoolValue("group", Group);
            writer.WriteIntValue("id", Id);
            writer.WriteObjectValue<global::NinjaOne.Client.V2.Billing.Invoices.InvoicesPostResponse_agreementProducts_integrationSettings>("integrationSettings", IntegrationSettings);
            writer.WriteStringValue("name", Name);
            writer.WriteDoubleValue("price", Price);
            writer.WriteIntValue("productId", ProductId);
            writer.WriteCollectionOfPrimitiveValues<int?>("productIds", ProductIds);
            writer.WriteDoubleValue("quantity", Quantity);
            writer.WriteStringValue("quantityType", QuantityType);
            writer.WriteDoubleValue("subTotal", SubTotal);
            writer.WriteDoubleValue("subTotalWithDiscount", SubTotalWithDiscount);
            writer.WriteBoolValue("taxable", Taxable);
            writer.WriteDoubleValue("taxRate", TaxRate);
            writer.WriteIntValue("ticketProductId", TicketProductId);
            writer.WriteDoubleValue("total", Total);
            writer.WriteDoubleValue("totalTax", TotalTax);
            writer.WriteStringValue("updateTime", UpdateTime);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
