// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent
{
    /// <summary>
    /// Policy condition script
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WindowsEvent_scripts : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Policy condition script runAs</summary>
        public global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEvent_scripts_runAs? RunAs { get; set; }
        /// <summary>Policy condition script id</summary>
        public int? ScriptId { get; set; }
        /// <summary>Policy condition script parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ScriptParam { get; set; }
#nullable restore
#else
        public string ScriptParam { get; set; }
#endif
        /// <summary>Policy condition script variables</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEvent_scripts_scriptVariables>? ScriptVariables { get; set; }
#nullable restore
#else
        public List<global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEvent_scripts_scriptVariables> ScriptVariables { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEvent_scripts"/> and sets the default values.
        /// </summary>
        public WindowsEvent_scripts()
        {
            AdditionalData = new Dictionary<string, object>();
            RunAs = global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEvent_scripts_runAs.SYSTEM;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEvent_scripts"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEvent_scripts CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEvent_scripts();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "runAs", n => { RunAs = n.GetEnumValue<global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEvent_scripts_runAs>(); } },
                { "scriptId", n => { ScriptId = n.GetIntValue(); } },
                { "scriptParam", n => { ScriptParam = n.GetStringValue(); } },
                { "scriptVariables", n => { ScriptVariables = n.GetCollectionOfObjectValues<global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEvent_scripts_scriptVariables>(global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEvent_scripts_scriptVariables.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEvent_scripts_runAs>("runAs", RunAs);
            writer.WriteIntValue("scriptId", ScriptId);
            writer.WriteStringValue("scriptParam", ScriptParam);
            writer.WriteCollectionOfObjectValues<global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEvent_scripts_scriptVariables>("scriptVariables", ScriptVariables);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
