// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent
{
    /// <summary>
    /// Windows event policy condition create request payload
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WindowsEventPostRequestBody : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Policy condition notification channels</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? Channels { get; set; }
#nullable restore
#else
        public List<int?> Channels { get; set; }
#endif
        /// <summary>Policy condition display name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>Policy condition enabled</summary>
        public bool? Enabled { get; set; }
        /// <summary>Event IDs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? EventIds { get; set; }
#nullable restore
#else
        public List<int?> EventIds { get; set; }
#endif
        /// <summary>Policy condition notification action</summary>
        public global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEventPostRequestBody_notificationAction? NotificationAction { get; set; }
        /// <summary>Policy condition notify on reset</summary>
        public bool? NotifyOnReset { get; set; }
        /// <summary>Windows event policy condition occurrence</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEventPostRequestBody_occurrence? Occurrence { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEventPostRequestBody_occurrence Occurrence { get; set; }
#endif
        /// <summary>Policy condition priority</summary>
        public global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEventPostRequestBody_priority? Priority { get; set; }
        /// <summary>Policy condition reset threshold (seconds)</summary>
        public int? ResetThreshold { get; set; }
        /// <summary>Policy condition scripts</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEventPostRequestBody_scripts>? Scripts { get; set; }
#nullable restore
#else
        public List<global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEventPostRequestBody_scripts> Scripts { get; set; }
#endif
        /// <summary>Policy condition severity</summary>
        public global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEventPostRequestBody_severity? Severity { get; set; }
        /// <summary>Event Source</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Source { get; set; }
#nullable restore
#else
        public string Source { get; set; }
#endif
        /// <summary>Windows event policy condition text</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEventPostRequestBody_text? Text { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEventPostRequestBody_text Text { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEventPostRequestBody"/> and sets the default values.
        /// </summary>
        public WindowsEventPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
            NotificationAction = global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEventPostRequestBody_notificationAction.NONE;
            Priority = global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEventPostRequestBody_priority.NONE;
            Severity = global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEventPostRequestBody_severity.NONE;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEventPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEventPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEventPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "channels", n => { Channels = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "displayName", n => { DisplayName = n.GetStringValue(); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "eventIds", n => { EventIds = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "notificationAction", n => { NotificationAction = n.GetEnumValue<global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEventPostRequestBody_notificationAction>(); } },
                { "notifyOnReset", n => { NotifyOnReset = n.GetBoolValue(); } },
                { "occurrence", n => { Occurrence = n.GetObjectValue<global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEventPostRequestBody_occurrence>(global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEventPostRequestBody_occurrence.CreateFromDiscriminatorValue); } },
                { "priority", n => { Priority = n.GetEnumValue<global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEventPostRequestBody_priority>(); } },
                { "resetThreshold", n => { ResetThreshold = n.GetIntValue(); } },
                { "scripts", n => { Scripts = n.GetCollectionOfObjectValues<global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEventPostRequestBody_scripts>(global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEventPostRequestBody_scripts.CreateFromDiscriminatorValue)?.AsList(); } },
                { "severity", n => { Severity = n.GetEnumValue<global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEventPostRequestBody_severity>(); } },
                { "source", n => { Source = n.GetStringValue(); } },
                { "text", n => { Text = n.GetObjectValue<global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEventPostRequestBody_text>(global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEventPostRequestBody_text.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<int?>("channels", Channels);
            writer.WriteStringValue("displayName", DisplayName);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteCollectionOfPrimitiveValues<int?>("eventIds", EventIds);
            writer.WriteEnumValue<global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEventPostRequestBody_notificationAction>("notificationAction", NotificationAction);
            writer.WriteBoolValue("notifyOnReset", NotifyOnReset);
            writer.WriteObjectValue<global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEventPostRequestBody_occurrence>("occurrence", Occurrence);
            writer.WriteEnumValue<global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEventPostRequestBody_priority>("priority", Priority);
            writer.WriteIntValue("resetThreshold", ResetThreshold);
            writer.WriteCollectionOfObjectValues<global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEventPostRequestBody_scripts>("scripts", Scripts);
            writer.WriteEnumValue<global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEventPostRequestBody_severity>("severity", Severity);
            writer.WriteStringValue("source", Source);
            writer.WriteObjectValue<global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEventPostRequestBody_text>("text", Text);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
