// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NinjaOne.Client.NinjaRmm.V2.SoftwareLicense.Upsert
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UpsertPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Indicates the names of assigned licensees and removes those not specified</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? CurrentLicensees { get; set; }
#nullable restore
#else
        public List<string> CurrentLicensees { get; set; }
#endif
        /// <summary>Indicates the current usage of the software license</summary>
        public int? CurrentUsage { get; set; }
        /// <summary>Indicates the purchase date of the software license in unix epoch milliseconds</summary>
        public long? Date { get; set; }
        /// <summary>Indicates a description for the software license</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Indicates the names of the licensees on which the license will be assigned</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? LicenseesToAssign { get; set; }
#nullable restore
#else
        public List<string> LicenseesToAssign { get; set; }
#endif
        /// <summary>Indicates the names of the licensees on which the license will be remowed</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? LicenseesToRemove { get; set; }
#nullable restore
#else
        public List<string> LicenseesToRemove { get; set; }
#endif
        /// <summary>Indicates the name of the software license</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Indicates a note about the software license</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Note { get; set; }
#nullable restore
#else
        public string Note { get; set; }
#endif
        /// <summary>Name of the publisher</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PublisherName { get; set; }
#nullable restore
#else
        public string PublisherName { get; set; }
#endif
        /// <summary>Indicates the quantity of the software license</summary>
        public int? Quantity { get; set; }
        /// <summary>Indicates the scope of the software license</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.NinjaRmm.V2.SoftwareLicense.Upsert.UpsertPostRequestBody_scope? Scope { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.NinjaRmm.V2.SoftwareLicense.Upsert.UpsertPostRequestBody_scope Scope { get; set; }
#endif
        /// <summary>Indicates the type of the software license</summary>
        public global::NinjaOne.Client.NinjaRmm.V2.SoftwareLicense.Upsert.UpsertPostRequestBody_type? Type { get; set; }
        /// <summary>Name of the vendor</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VendorName { get; set; }
#nullable restore
#else
        public string VendorName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.NinjaRmm.V2.SoftwareLicense.Upsert.UpsertPostRequestBody"/> and sets the default values.
        /// </summary>
        public UpsertPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NinjaOne.Client.NinjaRmm.V2.SoftwareLicense.Upsert.UpsertPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NinjaOne.Client.NinjaRmm.V2.SoftwareLicense.Upsert.UpsertPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::NinjaOne.Client.NinjaRmm.V2.SoftwareLicense.Upsert.UpsertPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "currentLicensees", n => { CurrentLicensees = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "currentUsage", n => { CurrentUsage = n.GetIntValue(); } },
                { "date", n => { Date = n.GetLongValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "licenseesToAssign", n => { LicenseesToAssign = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "licenseesToRemove", n => { LicenseesToRemove = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "note", n => { Note = n.GetStringValue(); } },
                { "publisherName", n => { PublisherName = n.GetStringValue(); } },
                { "quantity", n => { Quantity = n.GetIntValue(); } },
                { "scope", n => { Scope = n.GetObjectValue<global::NinjaOne.Client.NinjaRmm.V2.SoftwareLicense.Upsert.UpsertPostRequestBody_scope>(global::NinjaOne.Client.NinjaRmm.V2.SoftwareLicense.Upsert.UpsertPostRequestBody_scope.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::NinjaOne.Client.NinjaRmm.V2.SoftwareLicense.Upsert.UpsertPostRequestBody_type>(); } },
                { "vendorName", n => { VendorName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("currentLicensees", CurrentLicensees);
            writer.WriteIntValue("currentUsage", CurrentUsage);
            writer.WriteLongValue("date", Date);
            writer.WriteStringValue("description", Description);
            writer.WriteCollectionOfPrimitiveValues<string>("licenseesToAssign", LicenseesToAssign);
            writer.WriteCollectionOfPrimitiveValues<string>("licenseesToRemove", LicenseesToRemove);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("note", Note);
            writer.WriteStringValue("publisherName", PublisherName);
            writer.WriteIntValue("quantity", Quantity);
            writer.WriteObjectValue<global::NinjaOne.Client.NinjaRmm.V2.SoftwareLicense.Upsert.UpsertPostRequestBody_scope>("scope", Scope);
            writer.WriteEnumValue<global::NinjaOne.Client.NinjaRmm.V2.SoftwareLicense.Upsert.UpsertPostRequestBody_type>("type", Type);
            writer.WriteStringValue("vendorName", VendorName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
