// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NinjaOne.Client.V2.Billing.Agreements.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AgreementsGetResponse_contact : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The clientId property</summary>
        public int? ClientId { get; set; }
        /// <summary>The clientName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientName { get; set; }
#nullable restore
#else
        public string ClientName { get; set; }
#endif
        /// <summary>The deleted property</summary>
        public bool? Deleted { get; set; }
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The enabled property</summary>
        public bool? Enabled { get; set; }
        /// <summary>The firstName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstName { get; set; }
#nullable restore
#else
        public string FirstName { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The lastName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastName { get; set; }
#nullable restore
#else
        public string LastName { get; set; }
#endif
        /// <summary>The ninjaAdmin property</summary>
        public bool? NinjaAdmin { get; set; }
        /// <summary>The sysadmin property</summary>
        public bool? Sysadmin { get; set; }
        /// <summary>The uid property</summary>
        public Guid? Uid { get; set; }
        /// <summary>The userType property</summary>
        public global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsGetResponse_contact_userType? UserType { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsGetResponse_contact"/> and sets the default values.
        /// </summary>
        public AgreementsGetResponse_contact()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsGetResponse_contact"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsGetResponse_contact CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsGetResponse_contact();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "clientId", n => { ClientId = n.GetIntValue(); } },
                { "clientName", n => { ClientName = n.GetStringValue(); } },
                { "deleted", n => { Deleted = n.GetBoolValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "firstName", n => { FirstName = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "lastName", n => { LastName = n.GetStringValue(); } },
                { "ninjaAdmin", n => { NinjaAdmin = n.GetBoolValue(); } },
                { "sysadmin", n => { Sysadmin = n.GetBoolValue(); } },
                { "uid", n => { Uid = n.GetGuidValue(); } },
                { "userType", n => { UserType = n.GetEnumValue<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsGetResponse_contact_userType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("clientId", ClientId);
            writer.WriteStringValue("clientName", ClientName);
            writer.WriteBoolValue("deleted", Deleted);
            writer.WriteStringValue("email", Email);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteStringValue("firstName", FirstName);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("lastName", LastName);
            writer.WriteBoolValue("ninjaAdmin", NinjaAdmin);
            writer.WriteBoolValue("sysadmin", Sysadmin);
            writer.WriteGuidValue("uid", Uid);
            writer.WriteEnumValue<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsGetResponse_contact_userType>("userType", UserType);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
