// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace NinjaOne.Client.V2.Billing.Agreements.Item
{
    /// <summary>
    /// Representation of a ninja billing Agreement creation request.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AgreementsPutRequestBody : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether invoices generated from the agreement will be automatically approved when generated.</summary>
        public bool? AutoApproveInvoice { get; set; }
        /// <summary>Whether invoices generated from the agreement will be automatically completed when approved.</summary>
        public bool? AutoCompleteInvoice { get; set; }
        /// <summary>The backupStorageCountsProducts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_backupStorageCountsProducts>? BackupStorageCountsProducts { get; set; }
#nullable restore
#else
        public List<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_backupStorageCountsProducts> BackupStorageCountsProducts { get; set; }
#endif
        /// <summary>Hidden primary recipient email addresses to export to 3rd party integration when invoicing.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? BillBccEmails { get; set; }
#nullable restore
#else
        public List<string> BillBccEmails { get; set; }
#endif
        /// <summary>Copy recipient email addresses to export to 3rd party integration when invoicing.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? BillCcEmails { get; set; }
#nullable restore
#else
        public List<string> BillCcEmails { get; set; }
#endif
        /// <summary>Primary recipient email addresses to export to 3rd party integration when invoicing.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? BillEmails { get; set; }
#nullable restore
#else
        public List<string> BillEmails { get; set; }
#endif
        /// <summary>Where to pick business hours configuration, could be inherited from general configuration or custom.</summary>
        public global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_businessHoursSource? BusinessHoursSource { get; set; }
        /// <summary>ID of the organization owner of the agreement.</summary>
        public int? ClientId { get; set; }
        /// <summary>Representation of a ninja billing Agreement content request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_content? Content { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_content Content { get; set; }
#endif
        /// <summary>Agreement description.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The deviceCountsProducts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_deviceCountsProducts>? DeviceCountsProducts { get; set; }
#nullable restore
#else
        public List<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_deviceCountsProducts> DeviceCountsProducts { get; set; }
#endif
        /// <summary>Show time entries that have been billed against an included amount of hours on invoices.</summary>
        public bool? DisplayIncludedTimeOnInvoices { get; set; }
        /// <summary>How many days an invoice has to be payed after invoiced.</summary>
        public int? DueDays { get; set; }
        /// <summary>Where the agreement will obtain the information about due days.</summary>
        public global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_dueDaysSource? DueDaysSource { get; set; }
        /// <summary>The endUserCountsProducts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_endUserCountsProducts>? EndUserCountsProducts { get; set; }
#nullable restore
#else
        public List<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_endUserCountsProducts> EndUserCountsProducts { get; set; }
#endif
        /// <summary>How the agreement invoices will be generated.</summary>
        public global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_invoiceGenerationType? InvoiceGenerationType { get; set; }
        /// <summary>String message added to invoices generated from the agreement.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InvoiceNote { get; set; }
#nullable restore
#else
        public string InvoiceNote { get; set; }
#endif
        /// <summary>List of time entry quantity type products.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_laborTicketTimeEntryProducts>? LaborTicketTimeEntryProducts { get; set; }
#nullable restore
#else
        public List<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_laborTicketTimeEntryProducts> LaborTicketTimeEntryProducts { get; set; }
#endif
        /// <summary>List of backup storage count quantity type products.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_managedDeviceBackupProducts>? ManagedDeviceBackupProducts { get; set; }
#nullable restore
#else
        public List<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_managedDeviceBackupProducts> ManagedDeviceBackupProducts { get; set; }
#endif
        /// <summary>List of device count quantity type products.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_managedDeviceProducts>? ManagedDeviceProducts { get; set; }
#nullable restore
#else
        public List<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_managedDeviceProducts> ManagedDeviceProducts { get; set; }
#endif
        /// <summary>List of end user count quantity type products.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_managedEndUserProducts>? ManagedEndUserProducts { get; set; }
#nullable restore
#else
        public List<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_managedEndUserProducts> ManagedEndUserProducts { get; set; }
#endif
        /// <summary>Match multiple backup devices when counting to generate invoices.</summary>
        public bool? MultiMatchDeviceBackups { get; set; }
        /// <summary>Match multiple devices when counting to generate invoices.</summary>
        public bool? MultiMatchDevices { get; set; }
        /// <summary>Match multiple end user devices when counting to generate invoices.</summary>
        public bool? MultiMatchEndUsers { get; set; }
        /// <summary>Match multiple software licenses when counting to generate invoices.</summary>
        public bool? MultiMatchSoftwareLicenses { get; set; }
        /// <summary>Agreement name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>When the next invoice will be automatically generated.</summary>
        public Date? NextBillDate { get; set; }
        /// <summary>When the next billing period will start to count for the next invoice.</summary>
        public Date? NextBillingPeriodStartDate { get; set; }
        /// <summary>List of manual quantity type products.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_products>? Products { get; set; }
#nullable restore
#else
        public List<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_products> Products { get; set; }
#endif
        /// <summary>Quickbooks integration agreement specific data.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_quickBooks? QuickBooks { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_quickBooks QuickBooks { get; set; }
#endif
        /// <summary>Quickbooks integration agreement specific data.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_quickBooksAgreementIntegrationDataRequest? QuickBooksAgreementIntegrationDataRequest { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_quickBooksAgreementIntegrationDataRequest QuickBooksAgreementIntegrationDataRequest { get; set; }
#endif
        /// <summary>List of software license quantity type products.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_softwareLicenseProducts>? SoftwareLicenseProducts { get; set; }
#nullable restore
#else
        public List<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_softwareLicenseProducts> SoftwareLicenseProducts { get; set; }
#endif
        /// <summary>Representation of a ninja billing ticket settings request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_ticketBillingSettings? TicketBillingSettings { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_ticketBillingSettings TicketBillingSettings { get; set; }
#endif
        /// <summary>The timeEntriesProducts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_timeEntriesProducts>? TimeEntriesProducts { get; set; }
#nullable restore
#else
        public List<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_timeEntriesProducts> TimeEntriesProducts { get; set; }
#endif
        /// <summary>Xero integration agreement specific data.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_xero? Xero { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_xero Xero { get; set; }
#endif
        /// <summary>Xero integration agreement specific data.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_xeroAgreementIntegrationDataRequest? XeroAgreementIntegrationDataRequest { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_xeroAgreementIntegrationDataRequest XeroAgreementIntegrationDataRequest { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody"/> and sets the default values.
        /// </summary>
        public AgreementsPutRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "autoApproveInvoice", n => { AutoApproveInvoice = n.GetBoolValue(); } },
                { "autoCompleteInvoice", n => { AutoCompleteInvoice = n.GetBoolValue(); } },
                { "backupStorageCountsProducts", n => { BackupStorageCountsProducts = n.GetCollectionOfObjectValues<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_backupStorageCountsProducts>(global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_backupStorageCountsProducts.CreateFromDiscriminatorValue)?.AsList(); } },
                { "billBccEmails", n => { BillBccEmails = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "billCcEmails", n => { BillCcEmails = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "billEmails", n => { BillEmails = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "businessHoursSource", n => { BusinessHoursSource = n.GetEnumValue<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_businessHoursSource>(); } },
                { "clientId", n => { ClientId = n.GetIntValue(); } },
                { "content", n => { Content = n.GetObjectValue<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_content>(global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_content.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "deviceCountsProducts", n => { DeviceCountsProducts = n.GetCollectionOfObjectValues<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_deviceCountsProducts>(global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_deviceCountsProducts.CreateFromDiscriminatorValue)?.AsList(); } },
                { "displayIncludedTimeOnInvoices", n => { DisplayIncludedTimeOnInvoices = n.GetBoolValue(); } },
                { "dueDays", n => { DueDays = n.GetIntValue(); } },
                { "dueDaysSource", n => { DueDaysSource = n.GetEnumValue<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_dueDaysSource>(); } },
                { "endUserCountsProducts", n => { EndUserCountsProducts = n.GetCollectionOfObjectValues<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_endUserCountsProducts>(global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_endUserCountsProducts.CreateFromDiscriminatorValue)?.AsList(); } },
                { "invoiceGenerationType", n => { InvoiceGenerationType = n.GetEnumValue<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_invoiceGenerationType>(); } },
                { "invoiceNote", n => { InvoiceNote = n.GetStringValue(); } },
                { "laborTicketTimeEntryProducts", n => { LaborTicketTimeEntryProducts = n.GetCollectionOfObjectValues<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_laborTicketTimeEntryProducts>(global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_laborTicketTimeEntryProducts.CreateFromDiscriminatorValue)?.AsList(); } },
                { "managedDeviceBackupProducts", n => { ManagedDeviceBackupProducts = n.GetCollectionOfObjectValues<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_managedDeviceBackupProducts>(global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_managedDeviceBackupProducts.CreateFromDiscriminatorValue)?.AsList(); } },
                { "managedDeviceProducts", n => { ManagedDeviceProducts = n.GetCollectionOfObjectValues<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_managedDeviceProducts>(global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_managedDeviceProducts.CreateFromDiscriminatorValue)?.AsList(); } },
                { "managedEndUserProducts", n => { ManagedEndUserProducts = n.GetCollectionOfObjectValues<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_managedEndUserProducts>(global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_managedEndUserProducts.CreateFromDiscriminatorValue)?.AsList(); } },
                { "multiMatchDeviceBackups", n => { MultiMatchDeviceBackups = n.GetBoolValue(); } },
                { "multiMatchDevices", n => { MultiMatchDevices = n.GetBoolValue(); } },
                { "multiMatchEndUsers", n => { MultiMatchEndUsers = n.GetBoolValue(); } },
                { "multiMatchSoftwareLicenses", n => { MultiMatchSoftwareLicenses = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "nextBillDate", n => { NextBillDate = n.GetDateValue(); } },
                { "nextBillingPeriodStartDate", n => { NextBillingPeriodStartDate = n.GetDateValue(); } },
                { "products", n => { Products = n.GetCollectionOfObjectValues<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_products>(global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_products.CreateFromDiscriminatorValue)?.AsList(); } },
                { "quickBooks", n => { QuickBooks = n.GetObjectValue<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_quickBooks>(global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_quickBooks.CreateFromDiscriminatorValue); } },
                { "quickBooksAgreementIntegrationDataRequest", n => { QuickBooksAgreementIntegrationDataRequest = n.GetObjectValue<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_quickBooksAgreementIntegrationDataRequest>(global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_quickBooksAgreementIntegrationDataRequest.CreateFromDiscriminatorValue); } },
                { "softwareLicenseProducts", n => { SoftwareLicenseProducts = n.GetCollectionOfObjectValues<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_softwareLicenseProducts>(global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_softwareLicenseProducts.CreateFromDiscriminatorValue)?.AsList(); } },
                { "ticketBillingSettings", n => { TicketBillingSettings = n.GetObjectValue<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_ticketBillingSettings>(global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_ticketBillingSettings.CreateFromDiscriminatorValue); } },
                { "timeEntriesProducts", n => { TimeEntriesProducts = n.GetCollectionOfObjectValues<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_timeEntriesProducts>(global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_timeEntriesProducts.CreateFromDiscriminatorValue)?.AsList(); } },
                { "xero", n => { Xero = n.GetObjectValue<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_xero>(global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_xero.CreateFromDiscriminatorValue); } },
                { "xeroAgreementIntegrationDataRequest", n => { XeroAgreementIntegrationDataRequest = n.GetObjectValue<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_xeroAgreementIntegrationDataRequest>(global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_xeroAgreementIntegrationDataRequest.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("autoApproveInvoice", AutoApproveInvoice);
            writer.WriteBoolValue("autoCompleteInvoice", AutoCompleteInvoice);
            writer.WriteCollectionOfObjectValues<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_backupStorageCountsProducts>("backupStorageCountsProducts", BackupStorageCountsProducts);
            writer.WriteCollectionOfPrimitiveValues<string>("billBccEmails", BillBccEmails);
            writer.WriteCollectionOfPrimitiveValues<string>("billCcEmails", BillCcEmails);
            writer.WriteCollectionOfPrimitiveValues<string>("billEmails", BillEmails);
            writer.WriteEnumValue<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_businessHoursSource>("businessHoursSource", BusinessHoursSource);
            writer.WriteIntValue("clientId", ClientId);
            writer.WriteObjectValue<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_content>("content", Content);
            writer.WriteStringValue("description", Description);
            writer.WriteCollectionOfObjectValues<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_deviceCountsProducts>("deviceCountsProducts", DeviceCountsProducts);
            writer.WriteBoolValue("displayIncludedTimeOnInvoices", DisplayIncludedTimeOnInvoices);
            writer.WriteIntValue("dueDays", DueDays);
            writer.WriteEnumValue<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_dueDaysSource>("dueDaysSource", DueDaysSource);
            writer.WriteCollectionOfObjectValues<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_endUserCountsProducts>("endUserCountsProducts", EndUserCountsProducts);
            writer.WriteEnumValue<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_invoiceGenerationType>("invoiceGenerationType", InvoiceGenerationType);
            writer.WriteStringValue("invoiceNote", InvoiceNote);
            writer.WriteCollectionOfObjectValues<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_laborTicketTimeEntryProducts>("laborTicketTimeEntryProducts", LaborTicketTimeEntryProducts);
            writer.WriteCollectionOfObjectValues<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_managedDeviceBackupProducts>("managedDeviceBackupProducts", ManagedDeviceBackupProducts);
            writer.WriteCollectionOfObjectValues<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_managedDeviceProducts>("managedDeviceProducts", ManagedDeviceProducts);
            writer.WriteCollectionOfObjectValues<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_managedEndUserProducts>("managedEndUserProducts", ManagedEndUserProducts);
            writer.WriteBoolValue("multiMatchDeviceBackups", MultiMatchDeviceBackups);
            writer.WriteBoolValue("multiMatchDevices", MultiMatchDevices);
            writer.WriteBoolValue("multiMatchEndUsers", MultiMatchEndUsers);
            writer.WriteBoolValue("multiMatchSoftwareLicenses", MultiMatchSoftwareLicenses);
            writer.WriteStringValue("name", Name);
            writer.WriteDateValue("nextBillDate", NextBillDate);
            writer.WriteDateValue("nextBillingPeriodStartDate", NextBillingPeriodStartDate);
            writer.WriteCollectionOfObjectValues<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_products>("products", Products);
            writer.WriteObjectValue<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_quickBooks>("quickBooks", QuickBooks);
            writer.WriteObjectValue<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_quickBooksAgreementIntegrationDataRequest>("quickBooksAgreementIntegrationDataRequest", QuickBooksAgreementIntegrationDataRequest);
            writer.WriteCollectionOfObjectValues<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_softwareLicenseProducts>("softwareLicenseProducts", SoftwareLicenseProducts);
            writer.WriteObjectValue<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_ticketBillingSettings>("ticketBillingSettings", TicketBillingSettings);
            writer.WriteCollectionOfObjectValues<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_timeEntriesProducts>("timeEntriesProducts", TimeEntriesProducts);
            writer.WriteObjectValue<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_xero>("xero", Xero);
            writer.WriteObjectValue<global::NinjaOne.Client.V2.Billing.Agreements.Item.AgreementsPutRequestBody_xeroAgreementIntegrationDataRequest>("xeroAgreementIntegrationDataRequest", XeroAgreementIntegrationDataRequest);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
