// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using NinjaOne.Client.V2.Billing.TicketTimeEntry.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace NinjaOne.Client.V2.Billing.TicketTimeEntry
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\billing\ticket-time-entry
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TicketTimeEntryRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the NinjaOne.Client.v2.billing.ticketTimeEntry.item collection</summary>
        /// <param name="position">Time Entry ID</param>
        /// <returns>A <see cref="global::NinjaOne.Client.V2.Billing.TicketTimeEntry.Item.WithTimeEntryItemRequestBuilder"/></returns>
        public global::NinjaOne.Client.V2.Billing.TicketTimeEntry.Item.WithTimeEntryItemRequestBuilder this[long position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("timeEntryId", position);
                return new global::NinjaOne.Client.V2.Billing.TicketTimeEntry.Item.WithTimeEntryItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the NinjaOne.Client.v2.billing.ticketTimeEntry.item collection</summary>
        /// <param name="position">Time Entry ID</param>
        /// <returns>A <see cref="global::NinjaOne.Client.V2.Billing.TicketTimeEntry.Item.WithTimeEntryItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::NinjaOne.Client.V2.Billing.TicketTimeEntry.Item.WithTimeEntryItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("timeEntryId", position);
                return new global::NinjaOne.Client.V2.Billing.TicketTimeEntry.Item.WithTimeEntryItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.V2.Billing.TicketTimeEntry.TicketTimeEntryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TicketTimeEntryRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/billing/ticket-time-entry", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.V2.Billing.TicketTimeEntry.TicketTimeEntryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TicketTimeEntryRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/billing/ticket-time-entry", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
