// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NinjaOne.Client.V2.Automation.Scripts
{
    /// <summary>Script Variable Source</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Scripts_scriptVariables_source
    {
        [EnumMember(Value = "LITERAL")]
        #pragma warning disable CS1591
        LITERAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "OTHER")]
        #pragma warning disable CS1591
        OTHER,
        #pragma warning restore CS1591
    }
}
