// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NinjaOne.Client.V2.SoftwareLicense.Licenses
{
    /// <summary>
    /// List of software licenses
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LicensesGetResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The assigmentAutomationSettings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse_assigmentAutomationSettings? AssigmentAutomationSettings { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse_assigmentAutomationSettings AssigmentAutomationSettings { get; set; }
#endif
        /// <summary>Indicates if the software license assignment is automated</summary>
        public bool? Automated { get; set; }
        /// <summary>The automation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse_automation? Automation { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse_automation Automation { get; set; }
#endif
        /// <summary>Indicates the current usage of the software license</summary>
        public int? CurrentUsage { get; set; }
        /// <summary>Indicates the days to expire the software license</summary>
        public int? DaysToExpire { get; set; }
        /// <summary>Indicates a description for the software license</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Indicates itf the software license is expired</summary>
        public bool? Expired { get; set; }
        /// <summary>Indicates the identifier of the licensee</summary>
        public int? Id { get; set; }
        /// <summary>Indicates the name of the software license</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Indicates if exists notes of the software license</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Note { get; set; }
#nullable restore
#else
        public string Note { get; set; }
#endif
        /// <summary>The notificationChannelInfo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse_notificationChannelInfo? NotificationChannelInfo { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse_notificationChannelInfo NotificationChannelInfo { get; set; }
#endif
        /// <summary>The publisher property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse_publisher? Publisher { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse_publisher Publisher { get; set; }
#endif
        /// <summary>Indicates the purchase date of the software license in unix</summary>
        public long? PurchaseDate { get; set; }
        /// <summary>Indicates the quantity of the software license</summary>
        public int? Quantity { get; set; }
        /// <summary>The scope property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse_scope? Scope { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse_scope Scope { get; set; }
#endif
        /// <summary>The term property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse_term? Term { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse_term Term { get; set; }
#endif
        /// <summary>Indicates the type of the software license</summary>
        public global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse_type? Type { get; set; }
        /// <summary>The vendor property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse_vendor? Vendor { get; set; }
#nullable restore
#else
        public global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse_vendor Vendor { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse"/> and sets the default values.
        /// </summary>
        public LicensesGetResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "assigmentAutomationSettings", n => { AssigmentAutomationSettings = n.GetObjectValue<global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse_assigmentAutomationSettings>(global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse_assigmentAutomationSettings.CreateFromDiscriminatorValue); } },
                { "automated", n => { Automated = n.GetBoolValue(); } },
                { "automation", n => { Automation = n.GetObjectValue<global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse_automation>(global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse_automation.CreateFromDiscriminatorValue); } },
                { "currentUsage", n => { CurrentUsage = n.GetIntValue(); } },
                { "daysToExpire", n => { DaysToExpire = n.GetIntValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "expired", n => { Expired = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "note", n => { Note = n.GetStringValue(); } },
                { "notificationChannelInfo", n => { NotificationChannelInfo = n.GetObjectValue<global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse_notificationChannelInfo>(global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse_notificationChannelInfo.CreateFromDiscriminatorValue); } },
                { "publisher", n => { Publisher = n.GetObjectValue<global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse_publisher>(global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse_publisher.CreateFromDiscriminatorValue); } },
                { "purchaseDate", n => { PurchaseDate = n.GetLongValue(); } },
                { "quantity", n => { Quantity = n.GetIntValue(); } },
                { "scope", n => { Scope = n.GetObjectValue<global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse_scope>(global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse_scope.CreateFromDiscriminatorValue); } },
                { "term", n => { Term = n.GetObjectValue<global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse_term>(global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse_term.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse_type>(); } },
                { "vendor", n => { Vendor = n.GetObjectValue<global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse_vendor>(global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse_vendor.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse_assigmentAutomationSettings>("assigmentAutomationSettings", AssigmentAutomationSettings);
            writer.WriteBoolValue("automated", Automated);
            writer.WriteObjectValue<global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse_automation>("automation", Automation);
            writer.WriteIntValue("currentUsage", CurrentUsage);
            writer.WriteIntValue("daysToExpire", DaysToExpire);
            writer.WriteStringValue("description", Description);
            writer.WriteBoolValue("expired", Expired);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("note", Note);
            writer.WriteObjectValue<global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse_notificationChannelInfo>("notificationChannelInfo", NotificationChannelInfo);
            writer.WriteObjectValue<global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse_publisher>("publisher", Publisher);
            writer.WriteLongValue("purchaseDate", PurchaseDate);
            writer.WriteIntValue("quantity", Quantity);
            writer.WriteObjectValue<global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse_scope>("scope", Scope);
            writer.WriteObjectValue<global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse_term>("term", Term);
            writer.WriteEnumValue<global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse_type>("type", Type);
            writer.WriteObjectValue<global::NinjaOne.Client.V2.SoftwareLicense.Licenses.LicensesGetResponse_vendor>("vendor", Vendor);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
