// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace NinjaOne.Client.V2.Device.Item.OsPatches
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\device\{id}\os-patches
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OsPatchesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.V2.Device.Item.OsPatches.OsPatchesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OsPatchesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/device/{id}/os-patches{?severity*,status*,type*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.V2.Device.Item.OsPatches.OsPatchesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OsPatchesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/device/{id}/os-patches{?severity*,status*,type*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns list of pending/rejected/approved OS patches for device
        /// </summary>
        /// <returns>A List&lt;global::NinjaOne.Client.V2.Device.Item.OsPatches.OsPatches&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::NinjaOne.Client.V2.Device.Item.OsPatches.OsPatches>?> GetAsync(Action<RequestConfiguration<global::NinjaOne.Client.V2.Device.Item.OsPatches.OsPatchesRequestBuilder.OsPatchesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::NinjaOne.Client.V2.Device.Item.OsPatches.OsPatches>> GetAsync(Action<RequestConfiguration<global::NinjaOne.Client.V2.Device.Item.OsPatches.OsPatchesRequestBuilder.OsPatchesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::NinjaOne.Client.V2.Device.Item.OsPatches.OsPatches>(requestInfo, global::NinjaOne.Client.V2.Device.Item.OsPatches.OsPatches.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Returns list of pending/rejected/approved OS patches for device
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::NinjaOne.Client.V2.Device.Item.OsPatches.OsPatchesRequestBuilder.OsPatchesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::NinjaOne.Client.V2.Device.Item.OsPatches.OsPatchesRequestBuilder.OsPatchesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::NinjaOne.Client.V2.Device.Item.OsPatches.OsPatchesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::NinjaOne.Client.V2.Device.Item.OsPatches.OsPatchesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::NinjaOne.Client.V2.Device.Item.OsPatches.OsPatchesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns list of pending/rejected/approved OS patches for device
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class OsPatchesRequestBuilderGetQueryParameters 
        {
            /// <summary>Patch Severity filter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("severity")]
            public string? Severity { get; set; }
#nullable restore
#else
            [QueryParameter("severity")]
            public string Severity { get; set; }
#endif
            /// <summary>Patch Status filter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("status")]
            public string? Status { get; set; }
#nullable restore
#else
            [QueryParameter("status")]
            public string Status { get; set; }
#endif
            /// <summary>Patch Type filter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("type")]
            public string? Type { get; set; }
#nullable restore
#else
            [QueryParameter("type")]
            public string Type { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
