// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NinjaOne.Client.V2.SoftwareLicense.Item
{
    /// <summary>Indicates the cost mode of the software license</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WithLicensePutRequestBody_costMode
    {
        [EnumMember(Value = "TOTAL")]
        #pragma warning disable CS1591
        TOTAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "PER_LICENSE")]
        #pragma warning disable CS1591
        PER_LICENSE,
        #pragma warning restore CS1591
    }
}
