// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.CustomFields;
using NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.Item;
using NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\policies\{policy_id}\condition
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ConditionRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The customFields property</summary>
        public global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.CustomFields.CustomFieldsRequestBuilder CustomFields
        {
            get => new global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.CustomFields.CustomFieldsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The windowsEvent property</summary>
        public global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEventRequestBuilder WindowsEvent
        {
            get => new global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.WindowsEvent.WindowsEventRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the NinjaOne.Client.NinjaRmm.v2.policies.item.condition.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.Item.WithCondition_ItemRequestBuilder"/></returns>
        public global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.Item.WithCondition_ItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("condition_id", position);
                return new global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.Item.WithCondition_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the NinjaOne.Client.NinjaRmm.v2.policies.item.condition.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.Item.WithCondition_ItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.Item.WithCondition_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("condition_id", position);
                return new global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.Item.WithCondition_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.ConditionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConditionRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/policies/{policy_id}/condition", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.NinjaRmm.V2.Policies.Item.Condition.ConditionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConditionRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/policies/{policy_id}/condition", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
