// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NinjaOne.Client.V2.Users
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetUserTypeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "TECHNICIAN")]
        #pragma warning disable CS1591
        TECHNICIAN,
        #pragma warning restore CS1591
        [EnumMember(Value = "END_USER")]
        #pragma warning disable CS1591
        END_USER,
        #pragma warning restore CS1591
    }
}
