// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using NinjaOne.Client.NinjaRmm.V2.Device.Item.Patch.Software.Apply;
using NinjaOne.Client.NinjaRmm.V2.Device.Item.Patch.Software.Scan;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace NinjaOne.Client.NinjaRmm.V2.Device.Item.Patch.Software
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\device\{id}\patch\software
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SoftwareRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The apply property</summary>
        public global::NinjaOne.Client.NinjaRmm.V2.Device.Item.Patch.Software.Apply.ApplyRequestBuilder Apply
        {
            get => new global::NinjaOne.Client.NinjaRmm.V2.Device.Item.Patch.Software.Apply.ApplyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The scan property</summary>
        public global::NinjaOne.Client.NinjaRmm.V2.Device.Item.Patch.Software.Scan.ScanRequestBuilder Scan
        {
            get => new global::NinjaOne.Client.NinjaRmm.V2.Device.Item.Patch.Software.Scan.ScanRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.NinjaRmm.V2.Device.Item.Patch.Software.SoftwareRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SoftwareRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/device/{id}/patch/software", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.NinjaRmm.V2.Device.Item.Patch.Software.SoftwareRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SoftwareRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/device/{id}/patch/software", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
