// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace NinjaOne.Client.NinjaRmm.V2.Knowledgebase.Folder.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\knowledgebase\folder\{folderId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithFolderItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.NinjaRmm.V2.Knowledgebase.Folder.Item.WithFolderItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithFolderItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/knowledgebase/folder/{folderId}{?includeArchived*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.NinjaRmm.V2.Knowledgebase.Folder.Item.WithFolderItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithFolderItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/knowledgebase/folder/{folderId}{?includeArchived*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns knowledge base folder and its content
        /// </summary>
        /// <returns>A <see cref="global::NinjaOne.Client.NinjaRmm.V2.Knowledgebase.Folder.Item.WithFolderGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::NinjaOne.Client.NinjaRmm.V2.Knowledgebase.Folder.Item.WithFolderGetResponse?> GetAsWithFolderGetResponseAsync(Action<RequestConfiguration<global::NinjaOne.Client.NinjaRmm.V2.Knowledgebase.Folder.Item.WithFolderItemRequestBuilder.WithFolderItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::NinjaOne.Client.NinjaRmm.V2.Knowledgebase.Folder.Item.WithFolderGetResponse> GetAsWithFolderGetResponseAsync(Action<RequestConfiguration<global::NinjaOne.Client.NinjaRmm.V2.Knowledgebase.Folder.Item.WithFolderItemRequestBuilder.WithFolderItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::NinjaOne.Client.NinjaRmm.V2.Knowledgebase.Folder.Item.WithFolderGetResponse>(requestInfo, global::NinjaOne.Client.NinjaRmm.V2.Knowledgebase.Folder.Item.WithFolderGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns knowledge base folder and its content
        /// </summary>
        /// <returns>A <see cref="global::NinjaOne.Client.NinjaRmm.V2.Knowledgebase.Folder.Item.WithFolderResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use GetAsWithFolderGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::NinjaOne.Client.NinjaRmm.V2.Knowledgebase.Folder.Item.WithFolderResponse?> GetAsync(Action<RequestConfiguration<global::NinjaOne.Client.NinjaRmm.V2.Knowledgebase.Folder.Item.WithFolderItemRequestBuilder.WithFolderItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::NinjaOne.Client.NinjaRmm.V2.Knowledgebase.Folder.Item.WithFolderResponse> GetAsync(Action<RequestConfiguration<global::NinjaOne.Client.NinjaRmm.V2.Knowledgebase.Folder.Item.WithFolderItemRequestBuilder.WithFolderItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::NinjaOne.Client.NinjaRmm.V2.Knowledgebase.Folder.Item.WithFolderResponse>(requestInfo, global::NinjaOne.Client.NinjaRmm.V2.Knowledgebase.Folder.Item.WithFolderResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns knowledge base folder and its content
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::NinjaOne.Client.NinjaRmm.V2.Knowledgebase.Folder.Item.WithFolderItemRequestBuilder.WithFolderItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::NinjaOne.Client.NinjaRmm.V2.Knowledgebase.Folder.Item.WithFolderItemRequestBuilder.WithFolderItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::NinjaOne.Client.NinjaRmm.V2.Knowledgebase.Folder.Item.WithFolderItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::NinjaOne.Client.NinjaRmm.V2.Knowledgebase.Folder.Item.WithFolderItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::NinjaOne.Client.NinjaRmm.V2.Knowledgebase.Folder.Item.WithFolderItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns knowledge base folder and its content
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithFolderItemRequestBuilderGetQueryParameters 
        {
            [QueryParameter("includeArchived")]
            public bool? IncludeArchived { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithFolderItemRequestBuilderGetRequestConfiguration : RequestConfiguration<global::NinjaOne.Client.NinjaRmm.V2.Knowledgebase.Folder.Item.WithFolderItemRequestBuilder.WithFolderItemRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
