// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace NinjaOne.Client.V2.Queries.DeviceHealth
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\queries\device-health
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DeviceHealthRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.V2.Queries.DeviceHealth.DeviceHealthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeviceHealthRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/queries/device-health{?cursor*,df*,health*,pageSize*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.V2.Queries.DeviceHealth.DeviceHealthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeviceHealthRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/queries/device-health{?cursor*,df*,health*,pageSize*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns list of device health summary records
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::NinjaOne.Client.V2.Queries.DeviceHealth.DeviceHealth4XXError">When receiving a 4XX status code</exception>
        /// <exception cref="global::NinjaOne.Client.V2.Queries.DeviceHealth.DeviceHealth5XXError">When receiving a 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> GetAsync(Action<RequestConfiguration<global::NinjaOne.Client.V2.Queries.DeviceHealth.DeviceHealthRequestBuilder.DeviceHealthRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> GetAsync(Action<RequestConfiguration<global::NinjaOne.Client.V2.Queries.DeviceHealth.DeviceHealthRequestBuilder.DeviceHealthRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "4XX", global::NinjaOne.Client.V2.Queries.DeviceHealth.DeviceHealth4XXError.CreateFromDiscriminatorValue },
                { "5XX", global::NinjaOne.Client.V2.Queries.DeviceHealth.DeviceHealth5XXError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns list of device health summary records
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::NinjaOne.Client.V2.Queries.DeviceHealth.DeviceHealthRequestBuilder.DeviceHealthRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::NinjaOne.Client.V2.Queries.DeviceHealth.DeviceHealthRequestBuilder.DeviceHealthRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::NinjaOne.Client.V2.Queries.DeviceHealth.DeviceHealthRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::NinjaOne.Client.V2.Queries.DeviceHealth.DeviceHealthRequestBuilder WithUrl(string rawUrl)
        {
            return new global::NinjaOne.Client.V2.Queries.DeviceHealth.DeviceHealthRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns list of device health summary records
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DeviceHealthRequestBuilderGetQueryParameters 
        {
            /// <summary>Cursor name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("cursor")]
            public string? Cursor { get; set; }
#nullable restore
#else
            [QueryParameter("cursor")]
            public string Cursor { get; set; }
#endif
            /// <summary>Device filter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("df")]
            public string? Df { get; set; }
#nullable restore
#else
            [QueryParameter("df")]
            public string Df { get; set; }
#endif
            /// <summary>Health status filter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("health")]
            public string? Health { get; set; }
#nullable restore
#else
            [QueryParameter("health")]
            public string Health { get; set; }
#endif
            /// <summary>Limit number of records per page</summary>
            [QueryParameter("pageSize")]
            public int? PageSize { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DeviceHealthRequestBuilderGetRequestConfiguration : RequestConfiguration<global::NinjaOne.Client.V2.Queries.DeviceHealth.DeviceHealthRequestBuilder.DeviceHealthRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
