// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace NinjaOne.Client.V2.Device.Item.Processors
{
    /// <summary>
    /// Processors
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Processors : ApiException, IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Architecture</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Architecture { get; set; }
#nullable restore
#else
        public string Architecture { get; set; }
#endif
        /// <summary>Current Clock Speed</summary>
        public long? ClockSpeed { get; set; }
        /// <summary>Max Clock Speed</summary>
        public long? MaxClockSpeed { get; set; }
        /// <summary>The primary error message.</summary>
        public override string Message { get => base.Message; }
        /// <summary>Name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Number of Cores</summary>
        public int? NumCores { get; set; }
        /// <summary>Number of Logical Cores]</summary>
        public int? NumLogicalCores { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.V2.Device.Item.Processors.Processors"/> and sets the default values.
        /// </summary>
        public Processors()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NinjaOne.Client.V2.Device.Item.Processors.Processors"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NinjaOne.Client.V2.Device.Item.Processors.Processors CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::NinjaOne.Client.V2.Device.Item.Processors.Processors();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "architecture", n => { Architecture = n.GetStringValue(); } },
                { "clockSpeed", n => { ClockSpeed = n.GetLongValue(); } },
                { "maxClockSpeed", n => { MaxClockSpeed = n.GetLongValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "numCores", n => { NumCores = n.GetIntValue(); } },
                { "numLogicalCores", n => { NumLogicalCores = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("architecture", Architecture);
            writer.WriteLongValue("clockSpeed", ClockSpeed);
            writer.WriteLongValue("maxClockSpeed", MaxClockSpeed);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("numCores", NumCores);
            writer.WriteIntValue("numLogicalCores", NumLogicalCores);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
