// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using NinjaOne.Client.NinjaRmm.V2.CustomFields.EntityType.Item.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace NinjaOne.Client.NinjaRmm.V2.CustomFields.EntityType.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\custom-fields\entity-type\{entityType}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithEntityTypeItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the NinjaOne.Client.NinjaRmm.v2.customFields.entityType.item.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::NinjaOne.Client.NinjaRmm.V2.CustomFields.EntityType.Item.Item.WithEntityItemRequestBuilder"/></returns>
        public global::NinjaOne.Client.NinjaRmm.V2.CustomFields.EntityType.Item.Item.WithEntityItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("entityId", position);
                return new global::NinjaOne.Client.NinjaRmm.V2.CustomFields.EntityType.Item.Item.WithEntityItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the NinjaOne.Client.NinjaRmm.v2.customFields.entityType.item.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::NinjaOne.Client.NinjaRmm.V2.CustomFields.EntityType.Item.Item.WithEntityItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::NinjaOne.Client.NinjaRmm.V2.CustomFields.EntityType.Item.Item.WithEntityItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("entityId", position);
                return new global::NinjaOne.Client.NinjaRmm.V2.CustomFields.EntityType.Item.Item.WithEntityItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.NinjaRmm.V2.CustomFields.EntityType.Item.WithEntityTypeItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithEntityTypeItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/custom-fields/entity-type/{entityType}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.NinjaRmm.V2.CustomFields.EntityType.Item.WithEntityTypeItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithEntityTypeItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/custom-fields/entity-type/{entityType}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
