// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NinjaOne.Client.V2.RelatedItems.WithRelatedEntityType.Item
{
    /// <summary>Type of Relation</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WithRelatedEntityType_type
    {
        [EnumMember(Value = "VALUE")]
        #pragma warning disable CS1591
        VALUE,
        #pragma warning restore CS1591
        [EnumMember(Value = "ENTITY")]
        #pragma warning disable CS1591
        ENTITY,
        #pragma warning restore CS1591
    }
}
