// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NinjaOne.Client.V2.Itam.AssetRelationship.Item.Item.Relations
{
    /// <summary>Whether to get ingoing or outgoing relationships. By default, both sides are returned.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetSideQueryParameterType
    {
        [EnumMember(Value = "SOURCE")]
        #pragma warning disable CS1591
        SOURCE,
        #pragma warning restore CS1591
        [EnumMember(Value = "TARGET")]
        #pragma warning disable CS1591
        TARGET,
        #pragma warning restore CS1591
    }
}
