// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NinjaOne.Client.NinjaRmm.V2.Policies
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PoliciesPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Description</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Policy Enabled Flag</summary>
        public bool? Enabled { get; set; }
        /// <summary>Name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Node Class</summary>
        public global::NinjaOne.Client.NinjaRmm.V2.Policies.PoliciesPostRequestBody_nodeClass? NodeClass { get; set; }
        /// <summary>Parent Policy identifier</summary>
        public int? ParentPolicyId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::NinjaOne.Client.NinjaRmm.V2.Policies.PoliciesPostRequestBody"/> and sets the default values.
        /// </summary>
        public PoliciesPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NinjaOne.Client.NinjaRmm.V2.Policies.PoliciesPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NinjaOne.Client.NinjaRmm.V2.Policies.PoliciesPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::NinjaOne.Client.NinjaRmm.V2.Policies.PoliciesPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "description", n => { Description = n.GetStringValue(); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "nodeClass", n => { NodeClass = n.GetEnumValue<global::NinjaOne.Client.NinjaRmm.V2.Policies.PoliciesPostRequestBody_nodeClass>(); } },
                { "parentPolicyId", n => { ParentPolicyId = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("description", Description);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::NinjaOne.Client.NinjaRmm.V2.Policies.PoliciesPostRequestBody_nodeClass>("nodeClass", NodeClass);
            writer.WriteIntValue("parentPolicyId", ParentPolicyId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
